/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:22:50 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.Model.Music.Music;
import org.Model.Music.MusicReproduction;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistCreator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PlaylistCreator_ESTest extends PlaylistCreator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Random.setNextRandom((-1));
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      hashMap0.put("</zO", (Music) null);
      hashMap0.put("", (Music) null);
      List<Music> list0 = PlaylistCreator.createRandomPlaylist(hashMap0);
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        PlaylistCreator.createRandomPlaylist((Map<String, Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.PlaylistCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      // Undeclared exception!
      try { 
        PlaylistCreator.createRandomPlaylist(hashMap0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         assertThrownBy("org.evosuite.runtime.Random", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      linkedList0.add((MusicReproduction) null);
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      // Undeclared exception!
      try { 
        PlaylistCreator.createFavoritesPlaylist(3278, false, linkedList0, hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.PlaylistCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      linkedList0.add((MusicReproduction) null);
      // Undeclared exception!
      try { 
        PlaylistCreator.createFavoritesPlaylist(2478, true, linkedList0, hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.PlaylistCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      try { 
        PlaylistCreator.createFavoritesPlaylist(23, false, linkedList0, hashMap0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o h\u00E1 m\u00FAsicas favoritas suficientes.
         //
         assertThrownBy("org.Model.Playlist.PlaylistCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      hashMap0.put((String) null, (Music) null);
      // Undeclared exception!
      try { 
        PlaylistCreator.createGenrePlaylist((String) null, (String) null, (String) null, (-35), hashMap0, hashMap1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.PlaylistCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      // Undeclared exception!
      try { 
        PlaylistCreator.createGenrePlaylist((String) null, (String) null, (String) null, 0, hashMap0, hashMap1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o existem m\u00FAsicas desse g\u00E9nero.
         //
         assertThrownBy("org.Model.Playlist.PlaylistCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      PlaylistCreator playlistCreator0 = new PlaylistCreator();
  }
}
