/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:19:44 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Playlist_ESTest extends Playlist_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist(", autor='", ", autor='", (List<Music>) linkedList0);
      playlist0.setName((String) null);
      playlist0.getName();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist(", autor='", ", autor='", (List<Music>) linkedList0);
      playlist0.getName();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Playlist playlist0 = new Playlist("", "");
      Playlist playlist1 = new Playlist();
      int int0 = playlist1.getId();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist(", autor='", ", autor='", (List<Music>) linkedList0);
      playlist0.getAutor();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Playlist playlist0 = new Playlist(")3J1j%dq$", ")3J1j%dq$");
      assertEquals(0, playlist0.getId());
      
      playlist0.setId(1);
      playlist0.clone();
      assertEquals(1, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.setId((-1659));
      playlist0.clone();
      assertEquals(-1659, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.setMusics((List<Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      linkedList0.add((Music) null);
      playlist0.setMusics(linkedList0);
      // Undeclared exception!
      try { 
        playlist0.addMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Playlist playlist0 = null;
      try {
        playlist0 = new Playlist((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Playlist playlist0 = new Playlist("", "");
      int int0 = playlist0.getId();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Playlist playlist0 = new Playlist("`2", "`2");
      playlist0.addMusic((Music) null);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex(1094);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Playlist playlist0 = new Playlist("71:*PmvN$`!@.Q", "71:*PmvN$`!@.Q");
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex((-1682));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("LnvqR", "LnvqR", (List<Music>) linkedList0);
      Playlist playlist1 = playlist0.clone();
      assertTrue(playlist1.equals((Object)playlist0));
      
      playlist1.setAutor("No~m:");
      boolean boolean0 = playlist1.equals(playlist0);
      assertFalse(playlist1.equals((Object)playlist0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("9vR", "9vR", (List<Music>) linkedList0);
      Playlist playlist1 = new Playlist(playlist0);
      boolean boolean0 = playlist0.equals(playlist1);
      assertTrue(boolean0);
      assertEquals(0, playlist1.getId());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Playlist playlist0 = new Playlist("71:*PmvN$`!@.Q", "");
      assertEquals("71:*PmvN$`!@.Q", playlist0.getName());
      
      Playlist playlist1 = new Playlist("", (String) null, (List<Music>) null);
      boolean boolean0 = playlist1.equals(playlist0);
      assertEquals(1, playlist1.getId());
      assertEquals("", playlist0.getAutor());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Playlist playlist0 = new Playlist("71:*PmvN$`!@.Q", "");
      boolean boolean0 = playlist0.equals(playlist0);
      assertEquals("", playlist0.getAutor());
      assertEquals("71:*PmvN$`!@.Q", playlist0.getName());
      assertEquals(0, playlist0.getId());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Playlist playlist0 = new Playlist("", "");
      boolean boolean0 = playlist0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.getMusics();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      linkedList0.add((Music) null);
      Playlist playlist0 = new Playlist("lb-][q,V]", "lb-][q,V]", (List<Music>) linkedList0);
      boolean boolean0 = playlist0.removeMusic((Music) null);
      assertEquals(0, playlist0.getId());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Playlist playlist0 = new Playlist("lb-][q,V]", "lb-][q,V]", (List<Music>) linkedList0);
      playlist0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlist0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Playlist playlist0 = new Playlist("", (String) null, (List<Music>) null);
      String string0 = playlist0.getAutor();
      assertEquals(0, playlist0.getId());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.getName();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Playlist playlist0 = new Playlist("71:*PmvN$`!@.Q", "");
      playlist0.setName("");
      Playlist playlist1 = new Playlist("", (String) null, (List<Music>) null);
      // Undeclared exception!
      try { 
        playlist1.equals(playlist0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Playlist playlist0 = new Playlist("", "Interprete: ");
      assertEquals(0, playlist0.getId());
      
      playlist0.setId((-1));
      int int0 = playlist0.getId();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Playlist playlist0 = new Playlist("71:*PmvN$`!@.Q", "");
      playlist0.removeMusic((Music) null);
      assertEquals(0, playlist0.getId());
      assertEquals("", playlist0.getAutor());
      assertEquals("71:*PmvN$`!@.Q", playlist0.getName());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.hashCode();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Playlist playlist0 = new Playlist("71:*PmvN$`!@.Q", "");
      String string0 = playlist0.getAutor();
      assertEquals(0, playlist0.getId());
      assertEquals("71:*PmvN$`!@.Q", playlist0.getName());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Playlist playlist0 = new Playlist("", "Interprete: ");
      String string0 = playlist0.toString();
      assertEquals(0, playlist0.getId());
      assertEquals("Playlist{nome='', autor='Interprete: ', musicas=[]}", string0);
  }
}
