/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:21:36 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistFavorites;
import org.Model.Playlist.PlaylistRandom;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PlaylistFavorites_ESTest extends PlaylistFavorites_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites();
      List<Music> list0 = playlistFavorites0.getMusics();
      PlaylistFavorites playlistFavorites1 = new PlaylistFavorites(list0);
      PlaylistRandom playlistRandom0 = playlistFavorites1.clone();
      assertEquals(1, playlistRandom0.getId());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites((List<Music>) null);
      playlistFavorites0.setId((-1));
      PlaylistRandom playlistRandom0 = playlistFavorites0.clone();
      assertEquals("SpotifyUM", playlistRandom0.getAutor());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites();
      playlistFavorites0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlistFavorites0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites((List<Music>) null);
      PlaylistFavorites playlistFavorites1 = new PlaylistFavorites((Playlist) playlistFavorites0);
      playlistFavorites1.setAutor((String) null);
      // Undeclared exception!
      try { 
        playlistFavorites1.equals(playlistFavorites0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = null;
      try {
        playlistFavorites0 = new PlaylistFavorites((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites((List<Music>) null);
      boolean boolean0 = playlistFavorites0.equals(playlistFavorites0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites((List<Music>) null);
      Object object0 = new Object();
      boolean boolean0 = playlistFavorites0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites((List<Music>) null);
      PlaylistRandom playlistRandom0 = playlistFavorites0.clone();
      assertEquals("Feito para Voc\u00EA", playlistRandom0.getName());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      PlaylistFavorites playlistFavorites0 = new PlaylistFavorites();
      String string0 = playlistFavorites0.toString();
      assertEquals("Playlist Favoritos{nome='', autor='', musicas=[]}", string0);
  }
}
