/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:18:30 GMT 2026
 */

package org.Model.Playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistRandom;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PlaylistRandom_ESTest extends PlaylistRandom_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom("1uTZNbB&]", (List<Music>) null);
      PlaylistRandom playlistRandom1 = new PlaylistRandom();
      PlaylistRandom playlistRandom2 = playlistRandom1.clone();
      assertNotSame(playlistRandom2, playlistRandom0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      playlistRandom0.setId((-97));
      PlaylistRandom playlistRandom1 = playlistRandom0.clone();
      assertEquals("", playlistRandom1.getAutor());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistRandom playlistRandom0 = new PlaylistRandom("", (List<Music>) linkedList0);
      playlistRandom0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlistRandom0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      playlistRandom0.setName((String) null);
      PlaylistRandom playlistRandom1 = new PlaylistRandom((Playlist) playlistRandom0);
      // Undeclared exception!
      try { 
        playlistRandom0.equals(playlistRandom1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlaylistRandom playlistRandom0 = null;
      try {
        playlistRandom0 = new PlaylistRandom((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      PlaylistRandom playlistRandom1 = new PlaylistRandom((Playlist) playlistRandom0);
      boolean boolean0 = playlistRandom1.equals(playlistRandom0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      boolean boolean0 = playlistRandom0.equals(playlistRandom0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PlaylistRandom playlistRandom0 = new PlaylistRandom();
      boolean boolean0 = playlistRandom0.equals("Playlist Aleat\u00F3ria{nome='', autor='', musicas=[]}");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistRandom playlistRandom0 = new PlaylistRandom("", (List<Music>) linkedList0);
      PlaylistRandom playlistRandom1 = playlistRandom0.clone();
      assertTrue(playlistRandom1.equals((Object)playlistRandom0));
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      PlaylistRandom playlistRandom0 = new PlaylistRandom("", (List<Music>) linkedList0);
      String string0 = playlistRandom0.toString();
      assertEquals("Playlist Aleat\u00F3ria{nome='', autor='SpotifyUM', musicas=[]}", string0);
  }
}
