/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 27 15:45:48 GMT 2026
 */

package org.spotifumtp37.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonElement;
import com.google.gson.JsonSerializationContext;
import java.lang.reflect.Type;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Period;
import java.time.ZoneId;
import java.time.chrono.IsoChronology;
import java.time.format.DateTimeParseException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.evosuite.runtime.mock.java.time.MockLocalTime;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;
import org.spotifumtp37.util.LocalDateTimeAdapter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LocalDateTimeAdapter_ESTest extends LocalDateTimeAdapter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LocalDateTimeAdapter localDateTimeAdapter0 = new LocalDateTimeAdapter();
      // Undeclared exception!
      try { 
        localDateTimeAdapter0.serialize((LocalDateTime) null, (Type) null, (JsonSerializationContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.LocalDateTimeAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LocalDateTimeAdapter localDateTimeAdapter0 = new LocalDateTimeAdapter();
      JsonElement jsonElement0 = mock(JsonElement.class, new ViolatedAssumptionAnswer());
      doReturn("").when(jsonElement0).getAsString();
      Type type0 = mock(Type.class, new ViolatedAssumptionAnswer());
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        localDateTimeAdapter0.deserialize(jsonElement0, type0, jsonDeserializationContext0);
        fail("Expecting exception: DateTimeParseException");
      
      } catch(DateTimeParseException e) {
         //
         // Text '' could not be parsed at index 0
         //
         verifyException("java.time.format.DateTimeFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LocalDateTimeAdapter localDateTimeAdapter0 = new LocalDateTimeAdapter();
      Period period0 = Period.of(1, 2567, 1);
      IsoChronology isoChronology0 = period0.getChronology();
      ZoneId zoneId0 = ZoneId.systemDefault();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, zoneId0);
      LocalTime localTime0 = MockLocalTime.now(zoneId0);
      LocalDateTime localDateTime0 = MockLocalDateTime.of(localDate0, localTime0);
      Type type0 = mock(Type.class, new ViolatedAssumptionAnswer());
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonElement jsonElement0 = localDateTimeAdapter0.serialize(localDateTime0, type0, jsonSerializationContext0);
      Type type1 = mock(Type.class, new ViolatedAssumptionAnswer());
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      LocalDateTime localDateTime1 = localDateTimeAdapter0.deserialize(jsonElement0, type1, jsonDeserializationContext0);
      assertNotSame(localDateTime1, localDateTime0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LocalDateTimeAdapter localDateTimeAdapter0 = new LocalDateTimeAdapter();
      // Undeclared exception!
      try { 
        localDateTimeAdapter0.deserialize((JsonElement) null, (Type) null, (JsonDeserializationContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.LocalDateTimeAdapter", e);
      }
  }
}
