/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 27 15:43:24 GMT 2026
 */

package org.spotifumtp37.util;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class SongTypeAdapter_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.spotifumtp37.util.SongTypeAdapter"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/workspace"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SongTypeAdapter_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.gson.reflect.TypeToken",
      "com.google.gson.internal.bind.TypeAdapters$23",
      "com.google.gson.internal.reflect.ReflectionHelper$RecordNotSupportedHelper",
      "com.google.gson.internal.bind.TypeAdapters$24",
      "com.google.gson.ToNumberStrategy",
      "com.google.gson.internal.bind.TypeAdapters$25",
      "com.google.gson.internal.bind.TypeAdapters$26",
      "com.google.gson.internal.bind.TypeAdapters$20",
      "com.google.gson.internal.bind.JsonTreeWriter",
      "com.google.gson.TypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters$21",
      "com.google.gson.TypeAdapter$NullSafeTypeAdapter",
      "com.google.gson.JsonDeserializationContext",
      "com.google.gson.internal.bind.TypeAdapters$22",
      "com.google.gson.internal.bind.TypeAdapters$27",
      "com.google.gson.FieldNamingStrategy",
      "com.google.gson.internal.GsonTypes$GenericArrayTypeImpl",
      "com.google.gson.internal.bind.TypeAdapters$29",
      "com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper",
      "com.google.gson.internal.bind.NumberTypeAdapter$1",
      "com.google.gson.internal.bind.DefaultDateTypeAdapter$1",
      "org.spotifumtp37.model.album.ExplicitSong",
      "com.google.gson.internal.bind.EnumTypeAdapter",
      "com.google.gson.internal.TroubleshootingGuide",
      "com.google.gson.internal.bind.TypeAdapters$30",
      "com.google.gson.internal.bind.TypeAdapters$31",
      "com.google.gson.internal.bind.TypeAdapters$32",
      "com.google.gson.JsonArray",
      "com.google.gson.LongSerializationPolicy",
      "com.google.gson.internal.Excluder",
      "com.google.gson.internal.bind.SerializationDelegatingTypeAdapter",
      "com.google.gson.internal.LinkedTreeMap$EntrySet$1",
      "com.google.gson.internal.GsonTypes$ParameterizedTypeImpl",
      "com.google.gson.TypeAdapterFactory",
      "com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter",
      "com.google.gson.stream.JsonReader$1",
      "com.google.gson.internal.reflect.ReflectionHelper",
      "com.google.gson.internal.sql.SqlTypesSupport$2",
      "com.google.gson.internal.sql.SqlTypesSupport$1",
      "com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory$DummyTypeAdapterFactory",
      "com.google.gson.ReflectionAccessFilter$FilterResult",
      "com.google.gson.stream.JsonReader",
      "com.google.gson.internal.sql.SqlDateTypeAdapter",
      "com.google.gson.internal.bind.MapTypeAdapterFactory",
      "com.google.gson.Gson$FutureTypeAdapter",
      "com.google.gson.internal.bind.TreeTypeAdapter",
      "com.google.gson.internal.LinkedTreeMap$Node",
      "com.google.gson.stream.JsonWriter",
      "com.google.gson.internal.bind.ArrayTypeAdapter$1",
      "com.google.gson.internal.sql.SqlTimestampTypeAdapter$1",
      "com.google.gson.ToNumberPolicy",
      "com.google.gson.internal.Streams",
      "com.google.gson.internal.bind.TypeAdapters$12",
      "com.google.gson.internal.bind.TypeAdapters$13",
      "com.google.gson.internal.bind.TypeAdapters$14",
      "com.google.gson.internal.bind.DefaultDateTypeAdapter$DateType$1",
      "com.google.gson.internal.bind.TypeAdapters$15",
      "com.google.gson.internal.bind.TypeAdapters$10",
      "com.google.gson.internal.Primitives",
      "com.google.gson.internal.bind.TypeAdapters$11",
      "com.google.gson.stream.MalformedJsonException",
      "com.google.gson.internal.bind.ArrayTypeAdapter",
      "com.google.gson.stream.JsonToken",
      "com.google.gson.internal.bind.TypeAdapters$16",
      "com.google.gson.internal.bind.TypeAdapters$17",
      "com.google.gson.internal.ObjectConstructor",
      "com.google.gson.internal.bind.TypeAdapters$18",
      "com.google.gson.JsonNull",
      "com.google.gson.internal.bind.TypeAdapters$19",
      "com.google.gson.Strictness",
      "com.google.gson.LongSerializationPolicy$1",
      "com.google.gson.LongSerializationPolicy$2",
      "com.google.gson.internal.sql.SqlDateTypeAdapter$1",
      "com.google.gson.JsonObject",
      "com.google.gson.internal.bind.JsonTreeReader$2",
      "com.google.gson.internal.bind.JsonTreeReader$1",
      "com.google.gson.internal.UnsafeAllocator$3",
      "com.google.gson.internal.sql.SqlTypesSupport",
      "com.google.gson.internal.UnsafeAllocator$4",
      "com.google.gson.internal.ReflectionAccessFilterHelper",
      "com.google.gson.internal.UnsafeAllocator$1",
      "com.google.gson.internal.UnsafeAllocator$2",
      "com.google.gson.Gson$2",
      "com.google.gson.Gson$3",
      "com.google.gson.internal.bind.ObjectTypeAdapter",
      "com.google.gson.internal.bind.NumberTypeAdapter",
      "com.google.gson.JsonSerializer",
      "com.google.gson.Gson$4",
      "com.google.gson.Gson$5",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$RecordAdapter",
      "com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter",
      "com.google.gson.Gson$1",
      "com.google.gson.internal.reflect.ReflectionHelper$RecordHelper",
      "org.spotifumtp37.model.album.MultimediaSong",
      "com.google.gson.internal.sql.SqlTimeTypeAdapter$1",
      "com.google.gson.Gson",
      "com.google.gson.internal.GsonPreconditions",
      "com.google.gson.internal.LinkedTreeMap$1",
      "com.google.gson.internal.GsonTypes",
      "com.google.gson.internal.bind.DefaultDateTypeAdapter$DateType",
      "com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory",
      "com.google.gson.internal.sql.SqlTimestampTypeAdapter",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$BoundField",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory",
      "com.google.gson.internal.LinkedTreeMap$EntrySet",
      "com.google.gson.FormattingStyle",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1",
      "com.google.gson.annotations.SerializedName",
      "com.google.gson.internal.GsonTypes$WildcardTypeImpl",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldsData",
      "com.google.gson.internal.Excluder$1",
      "com.google.gson.internal.bind.TypeAdapters$2",
      "com.google.gson.internal.bind.JsonTreeReader",
      "com.google.gson.internal.bind.TypeAdapters$1",
      "com.google.gson.internal.bind.JsonTreeWriter$1",
      "com.google.gson.JsonIOException",
      "com.google.gson.internal.bind.TypeAdapters$8",
      "com.google.gson.internal.bind.TypeAdapters$7",
      "com.google.gson.internal.bind.TypeAdapters",
      "com.google.gson.internal.bind.TypeAdapters$9",
      "com.google.gson.ToNumberPolicy$1",
      "com.google.gson.internal.bind.TypeAdapters$4",
      "com.google.gson.internal.LinkedTreeMap",
      "com.google.gson.ToNumberPolicy$2",
      "com.google.gson.internal.bind.TypeAdapters$3",
      "com.google.gson.internal.bind.TypeAdapters$6",
      "com.google.gson.internal.LazilyParsedNumber",
      "com.google.gson.internal.bind.TypeAdapters$5",
      "com.google.gson.internal.bind.ObjectTypeAdapter$1",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter",
      "com.google.gson.JsonParseException",
      "com.google.gson.internal.sql.SqlTimeTypeAdapter",
      "com.google.gson.ToNumberPolicy$3",
      "com.google.gson.ToNumberPolicy$4",
      "com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper",
      "com.google.gson.internal.ConstructorConstructor",
      "com.google.gson.internal.bind.DefaultDateTypeAdapter",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter",
      "com.google.gson.internal.LinkedTreeMap$LinkedTreeMapIterator",
      "com.google.gson.JsonElement",
      "com.google.gson.FieldNamingPolicy",
      "com.google.gson.internal.bind.CollectionTypeAdapterFactory",
      "com.google.gson.JsonSerializationContext",
      "com.google.gson.annotations.JsonAdapter",
      "com.google.gson.JsonPrimitive",
      "com.google.gson.internal.bind.JsonElementTypeAdapter",
      "com.google.gson.internal.UnsafeAllocator",
      "com.google.gson.internal.Streams$AppendableWriter",
      "com.google.gson.JsonSyntaxException",
      "org.spotifumtp37.model.album.Song",
      "com.google.gson.internal.bind.EnumTypeAdapter$1",
      "com.google.gson.FieldNamingPolicy$4",
      "com.google.gson.FieldNamingPolicy$3",
      "com.google.gson.FieldNamingPolicy$6",
      "com.google.gson.FieldNamingPolicy$5",
      "com.google.gson.FieldNamingPolicy$7",
      "com.google.gson.internal.JsonReaderInternalAccess",
      "org.spotifumtp37.util.SongTypeAdapter",
      "com.google.gson.JsonDeserializer",
      "com.google.gson.internal.bind.TypeAdapters$32$1",
      "com.google.gson.FieldNamingPolicy$2",
      "com.google.gson.FieldNamingPolicy$1"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.google.gson.JsonDeserializationContext", false, SongTypeAdapter_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.google.gson.JsonElement", false, SongTypeAdapter_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.google.gson.JsonSerializationContext", false, SongTypeAdapter_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("java.lang.reflect.Type", false, SongTypeAdapter_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.spotifumtp37.model.album.MultimediaSong", false, SongTypeAdapter_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SongTypeAdapter_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.spotifumtp37.util.SongTypeAdapter",
      "com.google.gson.FormattingStyle",
      "com.google.gson.FieldNamingPolicy",
      "com.google.gson.ToNumberPolicy",
      "com.google.gson.Gson",
      "com.google.gson.internal.Excluder",
      "com.google.gson.LongSerializationPolicy",
      "com.google.gson.internal.ConstructorConstructor",
      "com.google.gson.TypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters$1",
      "com.google.gson.TypeAdapter$NullSafeTypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters$29",
      "com.google.gson.internal.bind.TypeAdapters$2",
      "com.google.gson.internal.bind.TypeAdapters$3",
      "com.google.gson.internal.bind.TypeAdapters$4",
      "com.google.gson.internal.bind.TypeAdapters$30",
      "com.google.gson.internal.bind.TypeAdapters$5",
      "com.google.gson.internal.bind.TypeAdapters$6",
      "com.google.gson.internal.bind.TypeAdapters$7",
      "com.google.gson.internal.bind.TypeAdapters$8",
      "com.google.gson.internal.bind.TypeAdapters$9",
      "com.google.gson.internal.bind.TypeAdapters$10",
      "com.google.gson.internal.bind.TypeAdapters$11",
      "com.google.gson.internal.bind.TypeAdapters$12",
      "com.google.gson.internal.bind.TypeAdapters$13",
      "com.google.gson.internal.bind.TypeAdapters$14",
      "com.google.gson.internal.bind.TypeAdapters$15",
      "com.google.gson.internal.bind.TypeAdapters$16",
      "com.google.gson.internal.bind.TypeAdapters$17",
      "com.google.gson.internal.bind.TypeAdapters$18",
      "com.google.gson.internal.bind.TypeAdapters$19",
      "com.google.gson.internal.bind.TypeAdapters$20",
      "com.google.gson.internal.bind.TypeAdapters$21",
      "com.google.gson.internal.bind.TypeAdapters$22",
      "com.google.gson.internal.bind.TypeAdapters$23",
      "com.google.gson.internal.bind.TypeAdapters$32",
      "com.google.gson.internal.bind.TypeAdapters$24",
      "com.google.gson.internal.bind.TypeAdapters$25",
      "com.google.gson.internal.bind.TypeAdapters$26",
      "com.google.gson.internal.bind.TypeAdapters$31",
      "com.google.gson.internal.bind.TypeAdapters$27",
      "com.google.gson.internal.bind.JsonElementTypeAdapter",
      "com.google.gson.internal.bind.EnumTypeAdapter$1",
      "com.google.gson.internal.bind.EnumTypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters",
      "com.google.gson.internal.bind.ObjectTypeAdapter$1",
      "com.google.gson.internal.bind.ObjectTypeAdapter",
      "com.google.gson.Gson$1",
      "com.google.gson.Gson$2",
      "com.google.gson.internal.bind.NumberTypeAdapter$1",
      "com.google.gson.internal.bind.NumberTypeAdapter",
      "com.google.gson.Gson$4",
      "com.google.gson.Gson$5",
      "com.google.gson.internal.bind.DefaultDateTypeAdapter$1",
      "com.google.gson.internal.bind.DefaultDateTypeAdapter",
      "com.google.gson.internal.bind.DefaultDateTypeAdapter$DateType$1",
      "com.google.gson.internal.bind.DefaultDateTypeAdapter$DateType",
      "com.google.gson.internal.sql.SqlTypesSupport$1",
      "com.google.gson.internal.sql.SqlTypesSupport$2",
      "com.google.gson.internal.sql.SqlDateTypeAdapter$1",
      "com.google.gson.internal.sql.SqlDateTypeAdapter",
      "com.google.gson.internal.sql.SqlTimeTypeAdapter$1",
      "com.google.gson.internal.sql.SqlTimeTypeAdapter",
      "com.google.gson.internal.sql.SqlTimestampTypeAdapter$1",
      "com.google.gson.internal.sql.SqlTimestampTypeAdapter",
      "com.google.gson.internal.sql.SqlTypesSupport",
      "com.google.gson.internal.bind.ArrayTypeAdapter$1",
      "com.google.gson.internal.bind.ArrayTypeAdapter",
      "com.google.gson.internal.bind.CollectionTypeAdapterFactory",
      "com.google.gson.internal.bind.MapTypeAdapterFactory",
      "com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory$DummyTypeAdapterFactory",
      "com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory",
      "org.spotifumtp37.model.album.Song",
      "com.google.gson.stream.JsonWriter",
      "com.google.gson.internal.bind.JsonTreeWriter$1",
      "com.google.gson.JsonElement",
      "com.google.gson.JsonPrimitive",
      "com.google.gson.internal.bind.JsonTreeWriter",
      "com.google.gson.Strictness",
      "com.google.gson.JsonNull",
      "com.google.gson.reflect.TypeToken",
      "com.google.gson.internal.GsonTypes",
      "com.google.gson.internal.bind.SerializationDelegatingTypeAdapter",
      "com.google.gson.Gson$FutureTypeAdapter",
      "com.google.gson.internal.reflect.ReflectionHelper$RecordHelper",
      "com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper",
      "com.google.gson.internal.reflect.ReflectionHelper$RecordNotSupportedHelper",
      "com.google.gson.internal.reflect.ReflectionHelper",
      "com.google.gson.internal.ReflectionAccessFilterHelper",
      "com.google.gson.ReflectionAccessFilter$FilterResult",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter",
      "com.google.gson.internal.Primitives",
      "com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$BoundField",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldsData",
      "com.google.gson.JsonObject",
      "com.google.gson.internal.LinkedTreeMap$1",
      "com.google.gson.internal.LinkedTreeMap",
      "com.google.gson.internal.LinkedTreeMap$Node",
      "com.google.gson.internal.Streams",
      "com.google.gson.internal.LinkedTreeMap$EntrySet",
      "com.google.gson.internal.LinkedTreeMap$LinkedTreeMapIterator",
      "com.google.gson.internal.LinkedTreeMap$EntrySet$1",
      "com.google.gson.internal.JsonReaderInternalAccess",
      "com.google.gson.stream.JsonReader$1",
      "com.google.gson.stream.JsonReader",
      "com.google.gson.internal.bind.JsonTreeReader$1",
      "com.google.gson.internal.bind.JsonTreeReader",
      "com.google.gson.stream.JsonToken",
      "org.spotifumtp37.model.album.MultimediaSong",
      "com.google.gson.internal.UnsafeAllocator$1",
      "com.google.gson.internal.UnsafeAllocator",
      "org.spotifumtp37.model.album.ExplicitSong",
      "com.google.gson.internal.GsonTypes$ParameterizedTypeImpl",
      "com.google.gson.internal.GsonPreconditions",
      "com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter",
      "com.google.gson.JsonArray",
      "com.google.gson.internal.GsonTypes$WildcardTypeImpl",
      "com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter",
      "com.google.gson.internal.TroubleshootingGuide",
      "com.google.gson.internal.GsonTypes$GenericArrayTypeImpl",
      "com.google.gson.stream.MalformedJsonException",
      "com.google.gson.JsonParseException",
      "com.google.gson.JsonSyntaxException",
      "com.google.gson.internal.bind.JsonTreeReader$2"
    );
  }
}
