/*
 * This file was automatically generated by EvoSuite
 * Wed May 06 17:07:58 GMT 2026
 */

package org.spotifumtp37.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import java.lang.reflect.Type;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.album.ExplicitSong;
import org.spotifumtp37.model.album.MultimediaSong;
import org.spotifumtp37.model.album.Song;
import org.spotifumtp37.util.SongTypeAdapter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SongTypeAdapter_ESTest extends SongTypeAdapter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      doReturn("Factory[typeHierarchy=").when(multimediaSong0).getArtist();
      doReturn(709).when(multimediaSong0).getDurationInSeconds();
      doReturn("M\"#Yloke.?bAdq").when(multimediaSong0).getGenre();
      doReturn("}").when(multimediaSong0).getLyrics();
      doReturn("M\"#Yloke.?bAdq").when(multimediaSong0).getMusicalNotes();
      doReturn("`hX`;y&B\"YYVlN?BPV").when(multimediaSong0).getName();
      doReturn("Factory[typeHierarchy=").when(multimediaSong0).getPublisher();
      doReturn(709).when(multimediaSong0).getTimesPlayed();
      MultimediaSong multimediaSong1 = new MultimediaSong(multimediaSong0);
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize((Song) multimediaSong1, (Type) null, jsonSerializationContext0);
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      songTypeAdapter0.deserialize(jsonObject0, (Type) null, jsonDeserializationContext0);
      assertEquals(9, jsonObject0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      doReturn("").when(multimediaSong0).getArtist();
      doReturn((-1)).when(multimediaSong0).getDurationInSeconds();
      doReturn("").when(multimediaSong0).getGenre();
      doReturn("org.spotifumtp37.model.album.MultimediaSong").when(multimediaSong0).getLyrics();
      doReturn("org.spotifumtp37.model.album.MultimediaSong").when(multimediaSong0).getMusicalNotes();
      doReturn("{R[").when(multimediaSong0).getName();
      doReturn("]6zbK><xbx1l").when(multimediaSong0).getPublisher();
      doReturn((-1)).when(multimediaSong0).getTimesPlayed();
      MultimediaSong multimediaSong1 = new MultimediaSong(multimediaSong0);
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize((Song) multimediaSong1, (Type) null, jsonSerializationContext0);
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      songTypeAdapter0.deserialize(jsonObject0, (Type) null, jsonDeserializationContext0);
      assertEquals(9, jsonObject0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        songTypeAdapter0.serialize((Song) multimediaSong0, (Type) null, jsonSerializationContext0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Attempted to serialize java.lang.Class: org.spotifumtp37.model.album.MultimediaSong. Forgot to register a type adapter?
         // See https://github.com/google/gson/blob/main/Troubleshooting.md#java-lang-class-unsupported
         //
         verifyException("com.google.gson.internal.bind.TypeAdapters$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      // Undeclared exception!
      try { 
        songTypeAdapter0.serialize((Song) null, (Type) null, (JsonSerializationContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.SongTypeAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      // Undeclared exception!
      try { 
        songTypeAdapter0.deserialize((JsonElement) null, (Type) null, (JsonDeserializationContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.SongTypeAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      Song song0 = new Song();
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize(song0, (Type) null, (JsonSerializationContext) null);
      songTypeAdapter0.deserialize(jsonObject0, (Type) null, (JsonDeserializationContext) null);
      assertEquals(8, jsonObject0.size());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(multimediaSong0).getArtist();
      doReturn(0).when(multimediaSong0).getDurationInSeconds();
      doReturn((String) null).when(multimediaSong0).getGenre();
      doReturn((String) null).when(multimediaSong0).getLyrics();
      doReturn((String) null).when(multimediaSong0).getMusicalNotes();
      doReturn((String) null).when(multimediaSong0).getName();
      doReturn((String) null).when(multimediaSong0).getPublisher();
      doReturn(0).when(multimediaSong0).getTimesPlayed();
      MultimediaSong multimediaSong1 = new MultimediaSong(multimediaSong0);
      multimediaSong1.setVideoLink("");
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize((Song) multimediaSong1, (Type) null, jsonSerializationContext0);
      songTypeAdapter0.deserialize(jsonObject0, (Type) null, (JsonDeserializationContext) null);
      assertEquals(4, jsonObject0.size());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      ExplicitSong explicitSong0 = new ExplicitSong("AaT#s-$?U^uy`", "AaT#s-$?U^uy`", "AaT#s-$?U^uy`", "AaT#s-$?U^uy`", "AaT#s-$?U^uy`", "AaT#s-$?U^uy`", 14);
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize((Song) explicitSong0, (Type) null, (JsonSerializationContext) null);
      songTypeAdapter0.deserialize(jsonObject0, (Type) null, (JsonDeserializationContext) null);
      assertEquals(9, jsonObject0.size());
  }
}
