/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 27 15:43:24 GMT 2026
 */

package org.spotifumtp37.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import java.lang.reflect.Type;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.album.ExplicitSong;
import org.spotifumtp37.model.album.MultimediaSong;
import org.spotifumtp37.model.album.Song;
import org.spotifumtp37.util.SongTypeAdapter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SongTypeAdapter_ESTest extends SongTypeAdapter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      ExplicitSong explicitSong0 = new ExplicitSong("5", (String) null, ")]}'\n", "", "", "R/", (-1));
      explicitSong0.setTimesPlayed((-1));
      Type type0 = mock(Type.class, new ViolatedAssumptionAnswer());
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize((Song) explicitSong0, type0, jsonSerializationContext0);
      Type type1 = mock(Type.class, new ViolatedAssumptionAnswer());
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      songTypeAdapter0.deserialize(jsonObject0, type1, jsonDeserializationContext0);
      assertEquals(8, jsonObject0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      doReturn("cB~4$H").when(multimediaSong0).getArtist();
      doReturn(1).when(multimediaSong0).getDurationInSeconds();
      doReturn("cB~4$H").when(multimediaSong0).getGenre();
      doReturn((String) null).when(multimediaSong0).getLyrics();
      doReturn("cB~4$H").when(multimediaSong0).getMusicalNotes();
      doReturn("cB~4$H").when(multimediaSong0).getName();
      doReturn("y 4{efv5yj*z\"OXO~Q").when(multimediaSong0).getPublisher();
      doReturn(1).when(multimediaSong0).getTimesPlayed();
      MultimediaSong multimediaSong1 = new MultimediaSong(multimediaSong0);
      Type type0 = mock(Type.class, new ViolatedAssumptionAnswer());
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize((Song) multimediaSong1, type0, jsonSerializationContext0);
      Type type1 = mock(Type.class, new ViolatedAssumptionAnswer());
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      songTypeAdapter0.deserialize(jsonObject0, type1, jsonDeserializationContext0);
      assertEquals(8, jsonObject0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      Type type0 = mock(Type.class, new ViolatedAssumptionAnswer());
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        songTypeAdapter0.serialize((Song) multimediaSong0, type0, jsonSerializationContext0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Attempted to serialize java.lang.Class: org.spotifumtp37.model.album.MultimediaSong. Forgot to register a type adapter?
         // See https://github.com/google/gson/blob/main/Troubleshooting.md#java-lang-class-unsupported
         //
         verifyException("com.google.gson.internal.bind.TypeAdapters$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      // Undeclared exception!
      try { 
        songTypeAdapter0.serialize((Song) null, (Type) null, (JsonSerializationContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.SongTypeAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      // Undeclared exception!
      try { 
        songTypeAdapter0.deserialize((JsonElement) null, (Type) null, (JsonDeserializationContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.SongTypeAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      ExplicitSong explicitSong0 = new ExplicitSong(",", ",", "q.SIiFbx|w@|aOMu#&9", "q.SIiFbx|w@|aOMu#&9", ",", "Bto", 0);
      Type type0 = mock(Type.class, new ViolatedAssumptionAnswer());
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      JsonElement jsonElement0 = songTypeAdapter0.serialize((Song) explicitSong0, type0, jsonSerializationContext0);
      JsonElement jsonElement1 = mock(JsonElement.class, new ViolatedAssumptionAnswer());
      doReturn(jsonElement0).when(jsonElement1).getAsJsonObject();
      Type type1 = mock(Type.class, new ViolatedAssumptionAnswer());
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      try { 
        songTypeAdapter0.deserialize(jsonElement1, type1, jsonDeserializationContext0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Custom JsonElement subclass com.google.gson.JsonElement$MockitoMock$1178938814 is not supported
         //
         verifyException("com.google.gson.Gson", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      ExplicitSong explicitSong0 = new ExplicitSong("&K)Ze>'8I}2;j,1+k8", "&K)Ze>'8I}2;j,1+k8", "&K)Ze>'8I}2;j,1+k8", "&K)Ze>'8I}2;j,1+k8", "&K)Ze>'8I}2;j,1+k8", "&K)Ze>'8I}2;j,1+k8", (-2365));
      Song song0 = new Song(explicitSong0);
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize(song0, (Type) null, (JsonSerializationContext) null);
      songTypeAdapter0.deserialize(jsonObject0, (Type) null, (JsonDeserializationContext) null);
      assertEquals(8, jsonObject0.size());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SongTypeAdapter songTypeAdapter0 = new SongTypeAdapter();
      MultimediaSong multimediaSong0 = mock(MultimediaSong.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(multimediaSong0).getArtist();
      doReturn(0).when(multimediaSong0).getDurationInSeconds();
      doReturn((String) null).when(multimediaSong0).getGenre();
      doReturn((String) null).when(multimediaSong0).getLyrics();
      doReturn((String) null).when(multimediaSong0).getMusicalNotes();
      doReturn((String) null).when(multimediaSong0).getName();
      doReturn((String) null).when(multimediaSong0).getPublisher();
      doReturn(0).when(multimediaSong0).getTimesPlayed();
      MultimediaSong multimediaSong1 = new MultimediaSong(multimediaSong0);
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      multimediaSong1.setVideoLink("org.spotifumtp37.util.SongTypeAdapter");
      JsonObject jsonObject0 = (JsonObject)songTypeAdapter0.serialize((Song) multimediaSong1, (Type) null, jsonSerializationContext0);
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      songTypeAdapter0.deserialize(jsonObject0, (Type) null, jsonDeserializationContext0);
      assertEquals(4, jsonObject0.size());
  }
}
