/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 27 15:44:36 GMT 2026
 */

package org.spotifumtp37.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import java.lang.reflect.Type;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.subscription.FreePlan;
import org.spotifumtp37.model.subscription.PremiumBase;
import org.spotifumtp37.model.subscription.PremiumTop;
import org.spotifumtp37.model.subscription.SubscriptionPlan;
import org.spotifumtp37.util.SubscriptionPlanAdapter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SubscriptionPlanAdapter_ESTest extends SubscriptionPlanAdapter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      Class<Integer> class0 = Integer.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(jsonDeserializationContext0).deserialize(any(com.google.gson.JsonElement.class) , any(java.lang.reflect.Type.class));
      SubscriptionPlan subscriptionPlan0 = subscriptionPlanAdapter0.deserialize(jsonObject0, class0, jsonDeserializationContext0);
      assertNull(subscriptionPlan0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      Class<Integer> class0 = Integer.TYPE;
      FreePlan freePlan0 = new FreePlan();
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(freePlan0).when(jsonDeserializationContext0).deserialize(any(com.google.gson.JsonElement.class) , any(java.lang.reflect.Type.class));
      SubscriptionPlan subscriptionPlan0 = subscriptionPlanAdapter0.deserialize(jsonObject0, class0, jsonDeserializationContext0);
      assertFalse(subscriptionPlan0.canCreatePlaylist());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      PremiumBase premiumBase0 = new PremiumBase();
      Class<Integer> class0 = Integer.TYPE;
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      doReturn((JsonElement) null).when(jsonSerializationContext0).serialize(any() , any(java.lang.reflect.Type.class));
      // Undeclared exception!
      try { 
        subscriptionPlanAdapter0.serialize((SubscriptionPlan) premiumBase0, (Type) class0, jsonSerializationContext0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.SubscriptionPlanAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      Class<Long> class0 = Long.TYPE;
      // Undeclared exception!
      try { 
        subscriptionPlanAdapter0.deserialize((JsonElement) null, class0, (JsonDeserializationContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.SubscriptionPlanAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(jsonObject0).when(jsonSerializationContext0).serialize(any() , any(java.lang.reflect.Type.class));
      PremiumBase premiumBase0 = new PremiumBase();
      Class<Long> class0 = Long.TYPE;
      subscriptionPlanAdapter0.serialize((SubscriptionPlan) premiumBase0, (Type) class0, jsonSerializationContext0);
      JsonElement jsonElement0 = jsonObject0.remove("type");
      // Undeclared exception!
      try { 
        subscriptionPlanAdapter0.deserialize(jsonElement0, class0, (JsonDeserializationContext) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Not a JSON Object: \"PremiumBase\"
         //
         verifyException("com.google.gson.JsonElement", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      Class<Short> class0 = Short.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(class0).when(jsonDeserializationContext0).deserialize(any(com.google.gson.JsonElement.class) , any(java.lang.reflect.Type.class));
      // Undeclared exception!
      try { 
        subscriptionPlanAdapter0.deserialize(jsonObject0, class0, jsonDeserializationContext0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Class cannot be cast to org.spotifumtp37.model.subscription.SubscriptionPlan
         //
         verifyException("org.spotifumtp37.util.SubscriptionPlanAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(jsonObject0).when(jsonSerializationContext0).serialize(any() , any(java.lang.reflect.Type.class));
      Class<Integer> class0 = Integer.TYPE;
      PremiumTop premiumTop0 = new PremiumTop();
      subscriptionPlanAdapter0.serialize((SubscriptionPlan) premiumTop0, (Type) class0, jsonSerializationContext0);
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(premiumTop0).when(jsonDeserializationContext0).deserialize(any(com.google.gson.JsonElement.class) , any(java.lang.reflect.Type.class));
      SubscriptionPlan subscriptionPlan0 = subscriptionPlanAdapter0.deserialize(jsonObject0, class0, jsonDeserializationContext0);
      assertTrue(subscriptionPlan0.canAccessFavouritesList());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      Class<Short> class0 = Short.TYPE;
      PremiumBase premiumBase0 = new PremiumBase();
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(jsonObject0).when(jsonSerializationContext0).serialize(any() , any(java.lang.reflect.Type.class));
      JsonElement jsonElement0 = subscriptionPlanAdapter0.serialize((SubscriptionPlan) premiumBase0, (Type) class0, jsonSerializationContext0);
      Class<Integer> class1 = Integer.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(jsonDeserializationContext0).deserialize(any(com.google.gson.JsonElement.class) , any(java.lang.reflect.Type.class));
      SubscriptionPlan subscriptionPlan0 = subscriptionPlanAdapter0.deserialize(jsonElement0, class1, jsonDeserializationContext0);
      //  // Unstable assertion: assertSame(premiumBase0, subscriptionPlan0);
  }
}
