/*
 * This file was automatically generated by EvoSuite
 * Wed May 06 17:09:07 GMT 2026
 */

package org.spotifumtp37.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializationContext;
import java.lang.reflect.Type;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.subscription.FreePlan;
import org.spotifumtp37.model.subscription.PremiumBase;
import org.spotifumtp37.model.subscription.PremiumTop;
import org.spotifumtp37.model.subscription.SubscriptionPlan;
import org.spotifumtp37.util.SubscriptionPlanAdapter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SubscriptionPlanAdapter_ESTest extends SubscriptionPlanAdapter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      FreePlan freePlan0 = new FreePlan();
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(freePlan0).when(jsonDeserializationContext0).deserialize(any(com.google.gson.JsonElement.class) , any(java.lang.reflect.Type.class));
      SubscriptionPlan subscriptionPlan0 = subscriptionPlanAdapter0.deserialize(jsonObject0, (Type) null, jsonDeserializationContext0);
      assertFalse(subscriptionPlan0.canBrowsePlaylist());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      Class<Long> class0 = Long.TYPE;
      Boolean boolean0 = new Boolean("");
      jsonObject0.addProperty("", boolean0);
      JsonPrimitive jsonPrimitive0 = jsonObject0.getAsJsonPrimitive("");
      PremiumTop premiumTop0 = new PremiumTop();
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(jsonPrimitive0).when(jsonSerializationContext0).serialize(any() , any(java.lang.reflect.Type.class));
      // Undeclared exception!
      try { 
        subscriptionPlanAdapter0.serialize((SubscriptionPlan) premiumTop0, (Type) class0, jsonSerializationContext0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
         //
         verifyException("org.spotifumtp37.util.SubscriptionPlanAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      jsonObject0.addProperty("", "");
      JsonElement jsonElement0 = jsonObject0.get("");
      Class<Character> class0 = Character.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        subscriptionPlanAdapter0.deserialize(jsonElement0, class0, jsonDeserializationContext0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Not a JSON Object: \"\"
         //
         verifyException("com.google.gson.JsonElement", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      Class<Long> class0 = Long.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(subscriptionPlanAdapter0).when(jsonDeserializationContext0).deserialize(any(com.google.gson.JsonElement.class) , any(java.lang.reflect.Type.class));
      // Undeclared exception!
      try { 
        subscriptionPlanAdapter0.deserialize(jsonObject0, class0, jsonDeserializationContext0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.spotifumtp37.util.SubscriptionPlanAdapter cannot be cast to org.spotifumtp37.model.subscription.SubscriptionPlan
         //
         verifyException("org.spotifumtp37.util.SubscriptionPlanAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      Class<Long> class0 = Long.TYPE;
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(jsonObject0).when(jsonSerializationContext0).serialize(any() , any(java.lang.reflect.Type.class));
      PremiumTop premiumTop0 = new PremiumTop();
      subscriptionPlanAdapter0.serialize((SubscriptionPlan) premiumTop0, (Type) class0, jsonSerializationContext0);
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(jsonDeserializationContext0).deserialize(any(com.google.gson.JsonElement.class) , any(java.lang.reflect.Type.class));
      SubscriptionPlan subscriptionPlan0 = subscriptionPlanAdapter0.deserialize(jsonObject0, class0, jsonDeserializationContext0);
      assertNull(subscriptionPlan0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      PremiumBase premiumBase0 = new PremiumBase();
      Class<Long> class0 = Long.TYPE;
      JsonSerializationContext jsonSerializationContext0 = mock(JsonSerializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(jsonObject0).when(jsonSerializationContext0).serialize(any() , any(java.lang.reflect.Type.class));
      JsonElement jsonElement0 = subscriptionPlanAdapter0.serialize((SubscriptionPlan) premiumBase0, (Type) class0, jsonSerializationContext0);
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(jsonDeserializationContext0).deserialize(any(com.google.gson.JsonElement.class) , any(java.lang.reflect.Type.class));
      SubscriptionPlan subscriptionPlan0 = subscriptionPlanAdapter0.deserialize(jsonElement0, class0, jsonDeserializationContext0);
      assertNull(subscriptionPlan0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      Class<Integer> class0 = Integer.TYPE;
      jsonObject0.addProperty("type", "type");
      // Undeclared exception!
      try { 
        subscriptionPlanAdapter0.deserialize(jsonObject0, class0, (JsonDeserializationContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.SubscriptionPlanAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      JsonObject jsonObject0 = new JsonObject();
      PremiumTop premiumTop0 = new PremiumTop();
      Class<Integer> class0 = Integer.TYPE;
      JsonDeserializationContext jsonDeserializationContext0 = mock(JsonDeserializationContext.class, new ViolatedAssumptionAnswer());
      doReturn(premiumTop0).when(jsonDeserializationContext0).deserialize(any(com.google.gson.JsonElement.class) , any(java.lang.reflect.Type.class));
      SubscriptionPlan subscriptionPlan0 = subscriptionPlanAdapter0.deserialize(jsonObject0, class0, jsonDeserializationContext0);
      assertSame(premiumTop0, subscriptionPlan0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SubscriptionPlanAdapter subscriptionPlanAdapter0 = new SubscriptionPlanAdapter();
      PremiumTop premiumTop0 = new PremiumTop();
      Class<Integer> class0 = Integer.TYPE;
      // Undeclared exception!
      try { 
        subscriptionPlanAdapter0.serialize((SubscriptionPlan) premiumTop0, (Type) class0, (JsonSerializationContext) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.SubscriptionPlanAdapter", e);
      }
  }
}
