/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:17:54 GMT 2026
 */

package org.Model.User;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.time.Month;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Music.MusicReproduction;
import org.Model.Plan.Plan;
import org.Model.Plan.PlanFree;
import org.Model.Plan.PlanPremiumBase;
import org.Model.Plan.PlanPremiumTop;
import org.Model.Playlist.Playlist;
import org.Model.User.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class User_ESTest extends User_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      User user0 = new User("", "", "", "");
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
      Month month0 = Month.JULY;
      LocalDate localDate1 = MockLocalDate.of(541, month0, 30);
      int int0 = user0.getMusicReproductionsCount(localDate0, localDate1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("eEt~:~YEn2`OoC", "YLK(Aw@lL", "", "f+&s47'tjz5(8*.<`AI", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist((String) null);
      try { 
        user0.removeMusicFromPlaylist((Music) null, 656);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 656
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("");
      try { 
        user0.getPlaylistById((-46));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -46
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uDCCB lai<ND", "\n  \uDCCB lai<ND", "'5wNI", "\n  \uDCCB lai<ND", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("org.Model.Plan.Plan");
      try { 
        user0.addMusicPlaylist(1, (Music) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 1
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      User user0 = new User("org.Exceptions.NotFoundException", "\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", "\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", "\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n");
      User user1 = new User(user0);
      assertEquals("\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", user1.getPassword());
      assertEquals("org.Exceptions.NotFoundException", user1.getUsername());
      assertEquals("\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", user1.getEmail());
      assertEquals("\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", user1.getAdress());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      User user0 = new User();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      user0.setPlan(planPremiumBase0);
      boolean boolean0 = user0.hasLibrary();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      User user0 = new User();
      user0.setUsername((String) null);
      String string0 = user0.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      User user0 = new User("j:Z8n18y3wW(w'", "d/}WZVc*H+M*S'", "d/}WZVc*H+M*S'", "j:Z8n18y3wW(w'");
      String string0 = user0.getUsername();
      assertEquals("j:Z8n18y3wW(w'", string0);
      assertEquals("d/}WZVc*H+M*S'", user0.getEmail());
      assertEquals("j:Z8n18y3wW(w'", user0.getPassword());
      assertEquals("d/}WZVc*H+M*S'", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      User user0 = new User("", "", "", "");
      List<Playlist> list0 = user0.getPlaylists();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("'5wNI");
      user0.addPlaylist("");
      Playlist playlist0 = user0.getPlaylistById(1);
      assertEquals("\n  \uD83D\uDCCB Plano: ", playlist0.getAutor());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getPassword());
      assertEquals(1, playlist0.getId());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getEmail());
      assertEquals("'5wNI", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop((Plan) planFree0);
      planPremiumTop0.setPoints((-533));
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", (String) null, "", "", (Plan) planPremiumTop0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      PlanPremiumTop planPremiumTop1 = (PlanPremiumTop)user0.getPlan();
      assertTrue(planPremiumTop1.hasAccessToFavorites());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      User user0 = new User("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", "", "", "\n  \uD83D\uDCE7 Email: ");
      String string0 = user0.getPassword();
      assertEquals("N\u00E3o tem permiss\u00E3o para aceder a este recurso: ", user0.getUsername());
      assertEquals("", user0.getAdress());
      assertEquals("\n  \uD83D\uDCE7 Email: ", string0);
      assertEquals("", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      User user0 = new User("MusicReproduction{music =", "MusicReproduction{music =", "MusicReproduction{music =", "BE6)9,");
      String string0 = user0.getEmail();
      assertEquals("MusicReproduction{music =", string0);
      assertEquals("BE6)9,", user0.getPassword());
      assertEquals("MusicReproduction{music =", user0.getUsername());
      assertEquals("MusicReproduction{music =", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase((Plan) planFree0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("", "", "", "", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      String string0 = user0.getAdress();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      User user0 = new User();
      user0.setPassword((String) null);
      // Undeclared exception!
      try { 
        user0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      linkedList1.add((MusicReproduction) null);
      User user0 = new User("\n  \uD83D\uDCCB Planop ", "\n  \uD83D\uDCCB Planop ", "'5wNI", "\n  \uD83D\uDCCB Planop ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      // Undeclared exception!
      try { 
        user0.setMusicReproductions(linkedList1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.removeMusicFromPlaylist((Music) null, 99);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB la}i<ND", "\n  \uD83D\uDCCB la}i<ND", "'5wNI", "\n  \uD83D\uDCCB la}i<ND", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.namePlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      User user0 = new User("fi-#SIfUdll5bT;g0#", "", "", "");
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.hasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.getUserPlaylistCount();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.getPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      User user0 = new User();
      user0.addMusicReproduction((Music) null);
      // Undeclared exception!
      try { 
        user0.getMusicReproductionsCount((LocalDate) null, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.time.chrono.ChronoLocalDate", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop((Plan) planPremiumBase0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      linkedList1.add((MusicReproduction) null);
      User user0 = new User("*UKcn`\"$}", "", "", "I4b", (Plan) planPremiumTop0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      // Undeclared exception!
      try { 
        user0.getMusicReproductions();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.changePlaylistAutor("\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 DADOS DO UTILIZADOR \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557\n  \uD83D\uDC64 Nome de Utilizador: \n  \uD83D\uDCE7 Email: \n  \uD83C\uDFE0 Morada: \n  \uD83D\uDD11 Password: \n  \uD83D\uDCCB Plano: Plano: Free\n    Pontos: 0\n\u255A\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255D");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      User user0 = new User("", "", (String) null, (String) null);
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.addPlaylistToLibrary((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      User user0 = new User();
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.addPlaylist("K|x{dq({h?MMl");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      linkedList0.add((Playlist) null);
      User user0 = null;
      try {
        user0 = new User("", "", "org.Exceptions.AlreadyExistsException", "", (Plan) planFree0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("");
      List<Playlist> list0 = user0.getPlaylists();
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getUsername());
      assertEquals("'5wNI", user0.getAdress());
      assertEquals(1, list0.size());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getEmail());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      User user0 = null;
      try {
        user0 = new User((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.addMusicPlaylist(0, (Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB la}i<ND", "\n  \uD83D\uDCCB la}i<ND", "'5wNI", "\n  \uD83D\uDCCB la}i<ND", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("'5wNI");
      user0.changePlaylistAutor("'5wNI");
      user0.changePlaylistAutor("y$y{n=ZK");
      assertEquals("'5wNI", user0.getAdress());
      assertEquals("\n  \uD83D\uDCCB la}i<ND", user0.getEmail());
      assertEquals("\n  \uD83D\uDCCB la}i<ND", user0.getUsername());
      assertEquals("\n  \uD83D\uDCCB la}i<ND", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("");
      user0.changePlaylistAutor("y$y{n=ZK");
      int int0 = user0.getUserPlaylistCount();
      assertEquals(0, int0);
      assertEquals("'5wNI", user0.getAdress());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getPassword());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getEmail());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("");
      int int0 = user0.getUserPlaylistCount();
      assertEquals(1, int0);
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getUsername());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getPassword());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getEmail());
      assertEquals("'5wNI", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB la}i<ND", "\n  \uD83D\uDCCB la}i<ND", "'5wNI", "\n  \uD83D\uDCCB la}i<ND", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("");
      try { 
        user0.removeMusicFromPlaylist((Music) null, (-2867));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -2867
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      User user0 = new User("", "", "", "");
      // Undeclared exception!
      try { 
        user0.getPlaylistById(2);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("");
      user0.changePlaylistAutor("y$y{n=ZK");
      try { 
        user0.addMusicPlaylist(0, (Music) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o tem permiss\u00E3o para aceder a este recurso: S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("eEt~:~YEn2`OoC", "YLK(Aw@lL", "", "f+&s47'tjz5(8*.<`AI", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist((String) null);
      try { 
        user0.addMusicPlaylist((-10), (Music) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -10
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("");
      user0.addMusicPlaylist(0, (Music) null);
      assertEquals("'5wNI", user0.getAdress());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getPassword());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getEmail());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.addPlaylist("Letra: ");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar playlists.
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("'5wNI");
      String string0 = user0.namePlaylists();
      assertEquals("\uD83C\uDFB5 [#000] '5wNI                     | Autor: \n  \uD83D\uDCCB Plano:   \n", string0);
      assertEquals("'5wNI", user0.getAdress());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getPassword());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.namePlaylists();
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getEmail());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getUsername());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getPassword());
      assertEquals("'5wNI", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.namePlaylists();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o possuem playlists.
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      User user0 = new User();
      boolean boolean0 = user0.equals(user0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      User user0 = new User();
      Object object0 = new Object();
      boolean boolean0 = user0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      User user0 = new User();
      user0.addMusicReproduction((Music) null);
      List<MusicReproduction> list0 = user0.getMusicReproductions();
      user0.setMusicReproductions(list0);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      User user0 = new User();
      List<MusicReproduction> list0 = user0.getMusicReproductions();
      user0.setMusicReproductions(list0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      linkedList1.add((MusicReproduction) null);
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      // Undeclared exception!
      try { 
        user0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      User user0 = new User();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      linkedList0.add((Playlist) null);
      // Undeclared exception!
      try { 
        user0.setPlaylists(linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      User user0 = new User();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      user0.setPlaylists(linkedList0);
      assertEquals("", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("'5wNI");
      User user1 = user0.clone();
      assertEquals("\n  \uD83D\uDCCB Plano: ", user1.getPassword());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user1.getUsername());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user1.getEmail());
      assertEquals("'5wNI", user1.getAdress());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.addPlaylist("");
      Playlist playlist0 = user0.getPlaylistById(0);
      linkedList0.add(playlist0);
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getEmail());
      assertEquals("'5wNI", user0.getAdress());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getPassword());
      
      User user1 = new User("\n  \uD83D\uDCCB Plano: ", "", "", "", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      assertEquals("", user1.getEmail());
      assertEquals("", user1.getPassword());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user1.getUsername());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      User user0 = new User();
      user0.setEmail((String) null);
      String string0 = user0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getEmail();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      User user0 = new User();
      user0.setAdress((String) null);
      assertEquals("", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      User user0 = new User("\t;2?^/27[[#", "\t;2?^/27[[#", "\t;2?^/27[[#", "\t;2?^/27[[#");
      String string0 = user0.toString();
      assertEquals("\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 DADOS DO UTILIZADOR \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557\n  \uD83D\uDC64 Nome de Utilizador: \t;2?^/27[[#\n  \uD83D\uDCE7 Email: \t;2?^/27[[#\n  \uD83C\uDFE0 Morada: \t;2?^/27[[#\n  \uD83D\uDD11 Password: \u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\n  \uD83D\uDCCB Plano: Plano: Free\n    Pontos: 0\n\u255A\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255D", string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      User user0 = new User("fi-#SIfUdll5bT;g0#", "", "", "");
      user0.hasLibrary();
      assertEquals("fi-#SIfUdll5bT;g0#", user0.getUsername());
      assertEquals("", user0.getAdress());
      assertEquals("", user0.getPassword());
      assertEquals("", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      LinkedList<MusicReproduction> linkedList1 = new LinkedList<MusicReproduction>();
      User user0 = new User("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "'5wNI", "\n  \uD83D\uDCCB Plano: ", (Plan) planPremiumBase0, (List<Playlist>) linkedList0, (List<MusicReproduction>) linkedList1);
      user0.getPlan();
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getUsername());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getEmail());
      assertEquals("\n  \uD83D\uDCCB Plano: ", user0.getPassword());
      assertEquals("'5wNI", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      User user0 = new User("\t;2?^/27[[#", "\t;2?^/27[[#", "\t;2?^/27[[#", "\t;2?^/27[[#");
      String string0 = user0.getAdress();
      assertEquals("\t;2?^/27[[#", string0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      User user0 = new User();
      user0.addPoints();
      PlanFree planFree0 = (PlanFree)user0.getPlan();
      assertFalse(planFree0.canChooseWhatToPlay());
  }
}
