/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:20:24 GMT 2026
 */

package org.Model.Music;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Music.Music;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Music_ESTest extends Music_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Music music0 = new Music();
      music0.setLyrics((String) null);
      music0.play();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Music music0 = new Music("", "", "O#a5>1=%wpEGO%[b", "\n", "", "Y|&8z.q>6RjQ4'$t", "", 1, true);
      music0.play();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "", 0, true);
      boolean boolean0 = music0.isExplicit();
      assertEquals(0, music0.getDuration());
      assertTrue(boolean0);
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Music music0 = new Music("", "_", "", "", "<b>.6_", "_", "", 0, true);
      music0.play();
      int int0 = music0.getReproductions();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "", 0, true);
      music0.setReproductions((-224));
      int int0 = music0.getReproductions();
      assertEquals((-224), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Music music0 = new Music(";g3[OG>QT", ";g3[OG>QT", "g8:f3RB6^WM.hcJ1W", "g8:f3RB6^WM.hcJ1W", "", "g8:f3RB6^WM.hcJ1W", "", (-1), false);
      assertEquals("g8:f3RB6^WM.hcJ1W", music0.getPublisher());
      
      music0.setPublisher((String) null);
      music0.getPublisher();
      assertEquals(";g3[OG>QT", music0.getInterpreter());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getMusicalFigures());
      assertEquals(";g3[OG>QT", music0.getName());
      assertEquals("g8:f3RB6^WM.hcJ1W", music0.getLyrics());
      assertEquals("", music0.getAlbum());
      assertEquals("g8:f3RB6^WM.hcJ1W", music0.getGenre());
      assertEquals(-1, music0.getDuration());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Music music0 = new Music("", (String) null, "~3Ev~};wT", (String) null, "8&30$YNf]Kmri>+}%c^", "", "&HPU2a", 0, false);
      String string0 = music0.getPublisher();
      assertEquals(0, music0.getDuration());
      assertEquals("", music0.getGenre());
      assertFalse(music0.isExplicit());
      assertEquals("8&30$YNf]Kmri>+}%c^", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
      assertEquals("&HPU2a", music0.getAlbum());
      assertEquals("", music0.getName());
      assertNotNull(string0);
      assertEquals("~3Ev~};wT", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Music music0 = new Music();
      music0.setName((String) null);
      music0.getName();
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Music music0 = new Music("-a45e.)^>A9-D]eJ3x-", "=ow6iV(&x'", "=ow6iV(&x'", "", "", "", (String) null, (-1321), false);
      String string0 = music0.getName();
      assertEquals("=ow6iV(&x'", music0.getInterpreter());
      assertEquals("", music0.getGenre());
      assertEquals("=ow6iV(&x'", music0.getPublisher());
      assertFalse(music0.isExplicit());
      assertEquals("", music0.getLyrics());
      assertNotNull(string0);
      assertEquals(-1321, music0.getDuration());
      assertEquals("-a45e.)^>A9-D]eJ3x-", string0);
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Music music0 = new Music("", "_", "", "", "<b>.6_", "_", "", 0, true);
      String string0 = music0.getMusicalFigures();
      assertEquals("_", music0.getInterpreter());
      assertEquals("", music0.getAlbum());
      assertEquals("<b>.6_", string0);
      assertEquals("_", music0.getGenre());
      assertEquals(0, music0.getDuration());
      assertEquals("", music0.getLyrics());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getPublisher());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Music music0 = new Music("-a45e.)^>A9-D]eJ3x-", "=ow6iV(&x'", "=ow6iV(&x'", "", "", "", (String) null, (-1321), false);
      String string0 = music0.getMusicalFigures();
      assertEquals("-a45e.)^>A9-D]eJ3x-", music0.getName());
      assertNotNull(string0);
      assertEquals("", music0.getLyrics());
      assertEquals(-1321, music0.getDuration());
      assertEquals("=ow6iV(&x'", music0.getInterpreter());
      assertFalse(music0.isExplicit());
      assertEquals("", string0);
      assertEquals("", music0.getGenre());
      assertEquals("=ow6iV(&x'", music0.getPublisher());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Music music0 = new Music("", (String) null, "~3Ev~};wT", (String) null, "8&30$YNf]Kmri>+}%c^", "", "&HPU2a", 0, false);
      String string0 = music0.getLyrics();
      assertEquals("8&30$YNf]Kmri>+}%c^", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
      assertEquals("&HPU2a", music0.getAlbum());
      assertFalse(music0.isExplicit());
      assertEquals("~3Ev~};wT", music0.getPublisher());
      assertNull(string0);
      assertEquals("", music0.getName());
      assertEquals(0, music0.getDuration());
      assertEquals("", music0.getGenre());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Music music0 = new Music("", "", "O#a5>1=%wpEGO%[b", "\n", "", "Y|&8z.q>6RjQ4'$t", "", 1, true);
      String string0 = music0.getLyrics();
      assertEquals("\n", string0);
      assertEquals(0, music0.getReproductions());
      assertEquals("O#a5>1=%wpEGO%[b", music0.getPublisher());
      assertEquals("Y|&8z.q>6RjQ4'$t", music0.getGenre());
      assertEquals("", music0.getAlbum());
      assertEquals("", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals(1, music0.getDuration());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("", music0.getInterpreter());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Music music0 = new Music();
      music0.setInterpreter("mE7`_yU");
      music0.getInterpreter();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Music music0 = new Music("]^E", "", "", "Genero Musical: ", (String) null, "", "", 1540, true);
      String string0 = music0.getInterpreter();
      assertEquals("", string0);
      assertEquals("", music0.getPublisher());
      assertEquals(0, music0.getReproductions());
      assertEquals("Genero Musical: ", music0.getLyrics());
      assertEquals("", music0.getAlbum());
      assertEquals("]^E", music0.getName());
      assertNotNull(string0);
      assertEquals(1540, music0.getDuration());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getGenre());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Music music0 = new Music("", "", "O#a5>1=%wpEGO%[b", "\n", "", "Y|&8z.q>6RjQ4'$t", "", 1, true);
      assertEquals("Y|&8z.q>6RjQ4'$t", music0.getGenre());
      
      music0.setGenre((String) null);
      music0.getGenre();
      assertEquals("", music0.getInterpreter());
      assertEquals("\n", music0.getLyrics());
      assertEquals(0, music0.getReproductions());
      assertEquals("O#a5>1=%wpEGO%[b", music0.getPublisher());
      assertEquals("", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals(1, music0.getDuration());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("", music0.getAlbum());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Music music0 = new Music("]^E", "", "", "Genero Musical: ", (String) null, "", "", 1540, true);
      String string0 = music0.getGenre();
      assertEquals("]^E", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getPublisher());
      assertEquals(0, music0.getReproductions());
      assertEquals("Genero Musical: ", music0.getLyrics());
      assertEquals("", music0.getInterpreter());
      assertEquals("", string0);
      assertEquals("", music0.getAlbum());
      assertEquals(1540, music0.getDuration());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Music music0 = new Music();
      music0.setDuration(550);
      int int0 = music0.getDuration();
      assertEquals(550, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Music music0 = new Music("", "", "", "Explicita: ", "Explicita: ", "%UP(2qdWiN2Dc", "%UP(2qdWiN2Dc", (-2117), true);
      int int0 = music0.getDuration();
      assertEquals("Explicita: ", music0.getLyrics());
      assertEquals("", music0.getPublisher());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getInterpreter());
      assertEquals("%UP(2qdWiN2Dc", music0.getGenre());
      assertEquals("", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals((-2117), int0);
      assertEquals("%UP(2qdWiN2Dc", music0.getAlbum());
      assertEquals("Explicita: ", music0.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Music music0 = new Music("-a45e.)^>A9-D]eJ3x-", "=ow6iV(&x'", "=ow6iV(&x'", "", "", "", (String) null, (-1321), false);
      String string0 = music0.getAlbum();
      assertNull(string0);
      assertEquals("=ow6iV(&x'", music0.getInterpreter());
      assertEquals("", music0.getGenre());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getLyrics());
      assertEquals("=ow6iV(&x'", music0.getPublisher());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("-a45e.)^>A9-D]eJ3x-", music0.getName());
      assertEquals(-1321, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Music music0 = new Music();
      music0.getAlbum();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Music music0 = new Music();
      music0.setReproductions((-2272));
      music0.clone();
      assertEquals(-2272, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Music music0 = null;
      try {
        music0 = new Music((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Music.Music", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Music music0 = new Music("", "Editora: ", "vr", "Editora: ", (String) null, "Genero Musical: ", "vr", 1849, false);
      String string0 = music0.getMusicalFigures();
      assertEquals("Editora: ", music0.getInterpreter());
      assertEquals("vr", music0.getPublisher());
      assertEquals("vr", music0.getAlbum());
      assertEquals("Editora: ", music0.getLyrics());
      assertEquals(1849, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertNull(string0);
      assertEquals("Genero Musical: ", music0.getGenre());
      assertFalse(music0.isExplicit());
      assertEquals("", music0.getName());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Music music0 = new Music("", "", "O#a5>1=%wpEGO%[b", "\n", "", "Y|&8z.q>6RjQ4'$t", "", 1, true);
      String string0 = music0.getGenre();
      assertEquals(1, music0.getDuration());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("", music0.getInterpreter());
      assertEquals("O#a5>1=%wpEGO%[b", music0.getPublisher());
      assertEquals("Y|&8z.q>6RjQ4'$t", string0);
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getAlbum());
      assertEquals("\n", music0.getLyrics());
      assertEquals("", music0.getName());
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Music music0 = new Music("", "Editora: ", "vr", "Editora: ", (String) null, "Genero Musical: ", "vr", 1849, false);
      Music music1 = new Music(music0);
      assertEquals("Editora: ", music1.getLyrics());
      assertFalse(music1.isExplicit());
      assertTrue(music1.equals((Object)music0));
      assertEquals(1849, music1.getDuration());
      assertEquals("Genero Musical: ", music1.getGenre());
      assertEquals("vr", music1.getPublisher());
      assertEquals("vr", music1.getAlbum());
      assertEquals(0, music1.getReproductions());
      assertEquals("Editora: ", music1.getInterpreter());
      assertEquals(1849, music0.getDuration());
      assertEquals("", music1.getName());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "", 0, true);
      int int0 = music0.getReproductions();
      assertEquals(0, int0);
      assertEquals(0, music0.getDuration());
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Music music0 = new Music("", (String) null, "~3Ev~};wT", (String) null, "8&30$YNf]Kmri>+}%c^", "", "&HPU2a", 0, false);
      String string0 = music0.getAlbum();
      assertEquals("~3Ev~};wT", music0.getPublisher());
      assertEquals(0, music0.getDuration());
      assertEquals("", music0.getGenre());
      assertNotNull(string0);
      assertEquals("&HPU2a", string0);
      assertFalse(music0.isExplicit());
      assertEquals("", music0.getName());
      assertEquals("8&30$YNf]Kmri>+}%c^", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Music music0 = new Music();
      music0.getName();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Music music0 = new Music();
      music0.getLyrics();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Music music0 = new Music("(lw,5l(_<aNE", "(lw,5l(_<aNE", "ST<)wE", "qa=", "(lw,5l(_<aNE", "Letra: ", "(lw,5l(_<aNE", 0, false);
      boolean boolean0 = music0.isExplicit();
      assertFalse(boolean0);
      assertEquals(0, music0.getReproductions());
      assertEquals("ST<)wE", music0.getPublisher());
      assertEquals("(lw,5l(_<aNE", music0.getMusicalFigures());
      assertEquals("qa=", music0.getLyrics());
      assertEquals("(lw,5l(_<aNE", music0.getAlbum());
      assertEquals(0, music0.getDuration());
      assertEquals("Letra: ", music0.getGenre());
      assertEquals("(lw,5l(_<aNE", music0.getInterpreter());
      assertEquals("(lw,5l(_<aNE", music0.getName());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, ",`zvd3[8QHNKqFzq<n", "?^asd/?", "FNS9uir#z~_q\"2NH~", "dq?4S+_b", "FNS9uir#z~_q\"2NH~", 0, true);
      String string0 = music0.getInterpreter();
      assertNull(string0);
      assertEquals("dq?4S+_b", music0.getGenre());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
      assertTrue(music0.isExplicit());
      assertEquals(",`zvd3[8QHNKqFzq<n", music0.getPublisher());
      assertEquals("?^asd/?", music0.getLyrics());
      assertEquals("FNS9uir#z~_q\"2NH~", music0.getMusicalFigures());
      assertEquals("FNS9uir#z~_q\"2NH~", music0.getAlbum());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Music music0 = new Music();
      music0.getPublisher();
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, ",`zvd3[8QHNKqFzq<n", "?^asd/?", "FNS9uir#z~_q\"2NH~", "dq?4S+_b", "FNS9uir#z~_q\"2NH~", 0, true);
      int int0 = music0.getDuration();
      assertEquals(0, int0);
      assertEquals(",`zvd3[8QHNKqFzq<n", music0.getPublisher());
      assertEquals("FNS9uir#z~_q\"2NH~", music0.getAlbum());
      assertEquals(0, music0.getReproductions());
      assertEquals("?^asd/?", music0.getLyrics());
      assertEquals("FNS9uir#z~_q\"2NH~", music0.getMusicalFigures());
      assertTrue(music0.isExplicit());
      assertEquals("dq?4S+_b", music0.getGenre());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, "|qj", "|qj", (String) null, "|qj", (String) null, (-11), true);
      Music music1 = music0.clone();
      music0.setName("|qj");
      boolean boolean0 = music1.equals(music0);
      assertFalse(music1.equals((Object)music0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Music music0 = new Music("FXAAd2T", "FXAAd2T", "FXAAd2T", "FXAAd2T", (String) null, "FXAAd2T", "FXAAd2T", 1, false);
      music0.setName((String) null);
      Music music1 = music0.clone();
      boolean boolean0 = music1.equals(music0);
      assertEquals(1, music0.getDuration());
      assertEquals(1, music1.getDuration());
      assertTrue(boolean0);
      assertEquals(0, music1.getReproductions());
      assertFalse(music1.isExplicit());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Music music0 = new Music("FXAAd2T", "FXAAd2T", "FXAAd2T", "FXAAd2T", (String) null, "FXAAd2T", "FXAAd2T", 1, false);
      Music music1 = music0.clone();
      boolean boolean0 = music1.equals(music0);
      assertEquals(1, music1.getDuration());
      assertEquals(1, music0.getDuration());
      assertFalse(music1.isExplicit());
      assertTrue(boolean0);
      assertEquals(0, music1.getReproductions());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Music music0 = new Music("FXAAd2T", "FXAAd2T", "FXAAd2T", "FXAAd2T", (String) null, "FXAAd2T", "FXAAd2T", 1, false);
      boolean boolean0 = music0.equals(music0);
      assertTrue(boolean0);
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(1, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Music music0 = new Music("", "_", "", "", "<b>.6_", "_", "", 0, true);
      boolean boolean0 = music0.equals("Nome: \nInterprete: _\nEditora: \nLetra: \nLinhas Musicais: <b>.6_\nGenero Musical: _\nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Sim\n");
      assertEquals("<b>.6_", music0.getMusicalFigures());
      assertEquals("_", music0.getInterpreter());
      assertFalse(boolean0);
      assertEquals("", music0.getAlbum());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getName());
      assertEquals("", music0.getLyrics());
      assertEquals("", music0.getPublisher());
      assertEquals("_", music0.getGenre());
      assertEquals(0, music0.getDuration());
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, ",`zvd3[8QHNKqFzq<n", "?^asd/?", "FNS9uir#z~_q\"2NH~", "dq?4S+_b", "FNS9uir#z~_q\"2NH~", 0, true);
      String string0 = music0.toString();
      assertEquals("Nome: null\nInterprete: null\nEditora: ,`zvd3[8QHNKqFzq<n\nLetra: ?^asd/?\nLinhas Musicais: FNS9uir#z~_q\"2NH~\nGenero Musical: dq?4S+_b\nAlbum: FNS9uir#z~_q\"2NH~\nDuracao: 0\nReproducoes: 0\nExplicita: Sim\n", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Music music0 = new Music("-a45e.)^>A9-D]eJ3x-", "=ow6iV(&x'", "=ow6iV(&x'", "", "", "", (String) null, (-1321), false);
      String string0 = music0.toString();
      assertEquals("Nome: -a45e.)^>A9-D]eJ3x-\nInterprete: =ow6iV(&x'\nEditora: =ow6iV(&x'\nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: null\nDuracao: -1321\nReproducoes: 0\nExplicita: Nao\n", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Music music0 = new Music();
      music0.setExplicit(false);
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Music music0 = new Music(";g3[OG>QT", ";g3[OG>QT", "g8:f3RB6^WM.hcJ1W", "g8:f3RB6^WM.hcJ1W", "", "g8:f3RB6^WM.hcJ1W", "", (-1), false);
      assertEquals("", music0.getMusicalFigures());
      
      music0.setMusicalFigures(";g3[OG>QT");
      assertEquals(";g3[OG>QT", music0.getName());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "", 0, true);
      music0.setAlbum("9q");
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Music music0 = new Music();
      music0.play();
      music0.clone();
      assertEquals(1, music0.getReproductions());
  }
}
