/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:19:07 GMT 2026
 */

package org.Model.Music;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import org.Model.Music.Music;
import org.Model.Music.MusicReproduction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MusicReproduction_ESTest extends MusicReproduction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MusicReproduction musicReproduction0 = null;
      try {
        musicReproduction0 = new MusicReproduction((MusicReproduction) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Music.MusicReproduction", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MusicReproduction musicReproduction0 = new MusicReproduction((Music) null);
      Music music0 = musicReproduction0.getMusic();
      assertNull(music0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MusicReproduction musicReproduction0 = new MusicReproduction((Music) null);
      MusicReproduction musicReproduction1 = musicReproduction0.clone();
      assertNotSame(musicReproduction0, musicReproduction1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MusicReproduction musicReproduction0 = new MusicReproduction((Music) null);
      musicReproduction0.setDate((LocalDate) null);
      LocalDate localDate0 = musicReproduction0.getDate();
      assertNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MusicReproduction musicReproduction0 = new MusicReproduction((Music) null);
      MusicReproduction musicReproduction1 = new MusicReproduction(musicReproduction0);
      assertFalse(musicReproduction1.equals((Object)musicReproduction0));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MusicReproduction musicReproduction0 = new MusicReproduction((Music) null);
      musicReproduction0.setMusic((Music) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MusicReproduction musicReproduction0 = new MusicReproduction((Music) null);
      LocalDate localDate0 = musicReproduction0.getDate();
      assertNotNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MusicReproduction musicReproduction0 = new MusicReproduction((Music) null, (LocalDate) null);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MusicReproduction musicReproduction0 = new MusicReproduction((Music) null);
      String string0 = musicReproduction0.toString();
      assertEquals("MusicReproduction{music =null,date =2014-02-14}", string0);
  }
}
