/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:16:39 GMT 2026
 */

package org.Model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.time.Period;
import java.time.chrono.IsoChronology;
import java.util.HashMap;
import java.util.Map;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistRandom;
import org.Model.SpotifUM;
import org.Model.User.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SpotifUM_ESTest extends SpotifUM_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addPlaylist("rC)$c,OZ", "}%(.?:?H2");
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewAlbum(",dt ", "");
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic("5*", "5*", (String) null, "S\u00F3 o autor da playlist pode remover m\u00FAsicas.", (String) null, "", "]gGZ9daOQT-RPm!+", (-1714), true, "]gGZ9daOQT-RPm!+");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      HashMap<String, Integer> hashMap5 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap5);
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<Integer, Playlist> hashMap0 = new HashMap<Integer, Playlist>();
      spotifUM0.setPublicPlaylists(hashMap0);
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap4);
      spotifUM0.setGenreReproductions(hashMap4);
      assertTrue(hashMap4.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<String, User> map0 = spotifUM0.getUsers();
      assertEquals(3, map0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("", (String) null, "", "");
      User user0 = spotifUM0.getUserWithMostPoints();
      assertEquals("", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<Integer, Playlist> map0 = spotifUM0.getPublicPlaylists();
      assertEquals(6, map0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      int int0 = spotifUM0.getPublicPlaylistSize();
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<String, Music> map0 = spotifUM0.getMusics();
      assertEquals(21, map0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementArtistReproductions("org.Exceptions.AlreadyExistsException");
      Map<String, Integer> map0 = spotifUM0.getArtistReproductions();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      hashMap0.put("\n  \uD83D\uDCCB Plano: ", (Album) null);
      spotifUM0.setAlbums(hashMap0);
      Map<String, Album> map0 = spotifUM0.getAlbums();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setPlaylistAsPublic(11);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setMusics((Map<String, Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setArtistReproductions((Map<String, Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.listAllMusicsInPlaylist(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.incrementGenreReproductions((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.TreeMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.changeCurrentUserName("\uD83D\uDCC0 Future Nostalgia \u2014 Dua Lipa\n\uD83D\uDCC0 Scorpion \u2014 Drake\n\uD83D\uDCC0 Fine Line \u2014 Harry Styles\n\uD83D\uDCC0 ASTROWORLD \u2014 Travis Scott\n\uD83D\uDCC0 Discovery \u2014 Daft Punk\n\uD83D\uDCC0 DAMN. \u2014 Kendrick Lamar\n\uD83D\uDCC0 The Marshall Mathers LP 2 \u2014 Eminem\n\uD83D\uDCC0 Rick Roll \u2014 Rick Astley\n\uD83D\uDCC0 Divide \u2014 Ed Sheeran\n\uD83D\uDCC0 A Night at the Opera \u2014 Queen\n\uD83D\uDCC0 After Hours \u2014 The Weeknd\n\uD83D\uDCC0 Hotel California \u2014 Eagles\n\uD83D\uDCC0 Thriller \u2014 Michael Jackson\n\uD83D\uDCC0 Tanto Porto! \u2014 FC Porto\n\uD83D\uDCC0 Led Zeppelin IV \u2014 Led Zeppelin\n\uD83D\uDCC0 Starboy \u2014 The Weeknd\n\uD83D\uDCC0 Appetite for Destruction \u2014 Guns N' Roses\n\uD83D\uDCC0 Nothing but the Beat \u2014 David Guetta\n\uD83D\uDCC0 Nevermind \u2014 Nirvana\n");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SpotifUM spotifUM0 = null;
      try {
        spotifUM0 = new SpotifUM((SpotifUM) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>(0);
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, Album> hashMap2 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap3 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = null;
      try {
        spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) null, (Map<String, Album>) hashMap2, (Map<String, Integer>) hashMap3, (Map<String, Integer>) hashMap3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<Integer, Playlist> map0 = spotifUM0.getPublicPlaylists();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = spotifUM0.getCurrentUser();
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, User> map0 = spotifUM0.getUsers();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Integer> map0 = spotifUM0.getArtistReproductions();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Music> map0 = spotifUM0.getMusics();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Album> map0 = spotifUM0.getAlbums();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Integer> map0 = spotifUM0.getGenreReproductions();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.equals(spotifUM0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Integer integer0 = Integer.getInteger("", 18);
      boolean boolean0 = spotifUM0.equals(integer0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap4);
      try { 
        spotifUM0.getUserWithMostReproductions();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      assertEquals("root", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Period period0 = Period.ZERO;
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      try { 
        spotifUM0.getUserWithMostReproductions(localDate0, localDate0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostPlaylists();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      assertEquals("root", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getGenreWithMostReproductions();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem reprodu\u00E7\u00F5es na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      Integer integer0 = new Integer((-1511));
      hashMap4.put("2{fI", integer0);
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap4);
      String string0 = spotifUM0.getGenreWithMostReproductions();
      assertEquals("2{fI", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostPoints();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("TGvJtN6@]", (User) null);
      spotifUM0.setUsers(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserWithMostPoints();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap4);
      try { 
        spotifUM0.getTopArtistName();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem artistas na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementArtistReproductions("org.Exceptions.AlreadyExistsException");
      String string0 = spotifUM0.getTopArtistName();
      assertEquals("org.Exceptions.AlreadyExistsException - 1\n", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.mostReproducedMusic();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem m\u00FAsicas na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllGenres();
      assertEquals("\u2022 Electronic\n\u2022 Hino\n\u2022 Hip-Hop\n\u2022 Pop\n\u2022 Rock\n", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      hashMap0.put("Du.!8*", (Music) null);
      spotifUM0.setMusics(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.listAllGenres();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllGenres();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listPublicPlaylists();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.addPlaylistToCurrentUserLibrary(2361);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 2361
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap4);
      try { 
        spotifUM0.addMusicToCurrentUserPlaylist((-1879048190), "Hino");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: Hino
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.getRandomPlaylist();
      PlaylistRandom playlistRandom0 = spotifUM0.getRandomPlaylist();
      assertEquals("Playlist Aleat\u00F3ria com 0 m\u00FAsicas.", playlistRandom0.getName());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.removeMusicFromPlaylist("Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", (Integer) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllAlbums();
      assertEquals("\uD83D\uDCC0 Future Nostalgia \u2014 Dua Lipa\n\uD83D\uDCC0 Scorpion \u2014 Drake\n\uD83D\uDCC0 Fine Line \u2014 Harry Styles\n\uD83D\uDCC0 ASTROWORLD \u2014 Travis Scott\n\uD83D\uDCC0 Discovery \u2014 Daft Punk\n\uD83D\uDCC0 DAMN. \u2014 Kendrick Lamar\n\uD83D\uDCC0 The Marshall Mathers LP 2 \u2014 Eminem\n\uD83D\uDCC0 Rick Roll \u2014 Rick Astley\n\uD83D\uDCC0 Divide \u2014 Ed Sheeran\n\uD83D\uDCC0 A Night at the Opera \u2014 Queen\n\uD83D\uDCC0 After Hours \u2014 The Weeknd\n\uD83D\uDCC0 Hotel California \u2014 Eagles\n\uD83D\uDCC0 Thriller \u2014 Michael Jackson\n\uD83D\uDCC0 Tanto Porto! \u2014 FC Porto\n\uD83D\uDCC0 Led Zeppelin IV \u2014 Led Zeppelin\n\uD83D\uDCC0 Starboy \u2014 The Weeknd\n\uD83D\uDCC0 Appetite for Destruction \u2014 Guns N' Roses\n\uD83D\uDCC0 Nothing but the Beat \u2014 David Guetta\n\uD83D\uDCC0 Nevermind \u2014 Nirvana\n", string0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllAlbums();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.addMusicToAlbum("", (Music) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getAlbumByName("yV>c[");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: yV>c[
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap4);
      boolean boolean0 = spotifUM0.albumExists("&RTY'p&4VF\"){7_*'");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllMusics();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic("Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", "N\u00E3o existem utilizadores na base de dados.", "", "", "|+\"`v@H|(pjfTJIi", "$,KxE[8\"Iz", "Letra: ", (-4281), true, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap4);
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic("1iA\"D1F2", "z65", "", "1iA\"D1F2", "V!PXu0X;be", "", "", 0, true, "Cl");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getMusicByName("zz[M,h`l vdqE+");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: zz[M,h`l vdqE+
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.playMusic("F7(GrhcOkn");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: F7(GrhcOkn
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.musicExists("b,~");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap4);
      boolean boolean0 = spotifUM0.userExists("Hino");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.authenticateUser("org.Exceptions.AlreadyExistsException", "E q~");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: org.Exceptions.AlreadyExistsException
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.createFavoritesPlaylist((-93), false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addToCurrentUserMusicReproductions("ZA:^2/e?gSu[[|");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getPublicPlaylistById(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getUserPlaylistById(1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.setCurrentUser((User) null);
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("8;n", "8;n", "tNjJ>DOt> $#w`(KY7", "");
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.canCurrentUserSkip();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.createGenrePlaylist("Rick Roll", "Rick Roll", (-3070));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.incrementArtistReproductions((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.TreeMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setGenreReproductions((Map<String, Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserPassword("tNjJ>DOt> $#w`(KY7");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getCurrentUserPlanName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setPublicPlaylists((Map<Integer, Playlist>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addToCurrentUserPlaylist("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.listCurrentUserPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.toString();
      assertEquals("SpotifUM(...)", string0);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      spotifUM0.setArtistReproductions(hashMap0);
      assertEquals(0, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.isPasswordCorrect("fK:awR!4h 1_T[*N");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setAlbums((Map<String, Album>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addPlaylist(",date =", ",date =");
      String string0 = spotifUM0.listPublicPlaylists();
      assertEquals("\uD83C\uDFB5 [#000] ,date =                   | Autor: ,date =        \n", string0);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.hasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.currentUserAccessToFavorites();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserEmail("\uD83C\uDFB6 Levitating \u2014 Dua Lipa\n\uD83C\uDFB6 Sweet Child O' Mine \u2014 Guns N' Roses\n\uD83C\uDFB6 Rap God \u2014 Eminem\n\uD83C\uDFB6 Bohemian Rhapsody \u2014 Queen\n\uD83C\uDFB6 Billie Jean \u2014 Michael Jackson\n\uD83C\uDFB6 Don't Start Now \u2014 Dua Lipa\n\uD83C\uDFB6 Blinding Lights \u2014 The Weeknd\n\uD83C\uDFB6 Hino do Futebol Clube do Porto \u2014 Maria Am\u00E9lia Canossa\n\uD83C\uDFB6 Shape of You \u2014 Ed Sheeran\n\uD83C\uDFB6 One More Time \u2014 Daft Punk\n\uD83C\uDFB6 Hotel California \u2014 Eagles\n\uD83C\uDFB6 Beat It \u2014 Michael Jackson\n\uD83C\uDFB6 Stairway to Heaven \u2014 Led Zeppelin\n\uD83C\uDFB6 Never Gonna Give You Up \u2014 Rick Astley\n\uD83C\uDFB6 God's Plan \u2014 Drake\n\uD83C\uDFB6 Titanium \u2014 David Guetta\n\uD83C\uDFB6 SICKO MODE \u2014 Travis Scott\n\uD83C\uDFB6 Starboy \u2014 The Weeknd\n\uD83C\uDFB6 HUMBLE. \u2014 Kendrick Lamar\n\uD83C\uDFB6 Watermelon Sugar \u2014 Harry Styles\n\uD83C\uDFB6 Smells Like Teen Spirit \u2014 Nirvana\n");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addPointsToCurrentUser();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      SpotifUM spotifUM1 = new SpotifUM(spotifUM0);
      assertTrue(spotifUM1.equals((Object)spotifUM0));
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.canCurrentUserChooseWhatToPlay();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllMusics();
      assertEquals("\uD83C\uDFB6 Levitating \u2014 Dua Lipa\n\uD83C\uDFB6 Sweet Child O' Mine \u2014 Guns N' Roses\n\uD83C\uDFB6 Rap God \u2014 Eminem\n\uD83C\uDFB6 Bohemian Rhapsody \u2014 Queen\n\uD83C\uDFB6 Billie Jean \u2014 Michael Jackson\n\uD83C\uDFB6 Don't Start Now \u2014 Dua Lipa\n\uD83C\uDFB6 Blinding Lights \u2014 The Weeknd\n\uD83C\uDFB6 Hino do Futebol Clube do Porto \u2014 Maria Am\u00E9lia Canossa\n\uD83C\uDFB6 Shape of You \u2014 Ed Sheeran\n\uD83C\uDFB6 One More Time \u2014 Daft Punk\n\uD83C\uDFB6 Hotel California \u2014 Eagles\n\uD83C\uDFB6 Beat It \u2014 Michael Jackson\n\uD83C\uDFB6 Stairway to Heaven \u2014 Led Zeppelin\n\uD83C\uDFB6 Never Gonna Give You Up \u2014 Rick Astley\n\uD83C\uDFB6 God's Plan \u2014 Drake\n\uD83C\uDFB6 Titanium \u2014 David Guetta\n\uD83C\uDFB6 SICKO MODE \u2014 Travis Scott\n\uD83C\uDFB6 Starboy \u2014 The Weeknd\n\uD83C\uDFB6 HUMBLE. \u2014 Kendrick Lamar\n\uD83C\uDFB6 Watermelon Sugar \u2014 Harry Styles\n\uD83C\uDFB6 Smells Like Teen Spirit \u2014 Nirvana\n", string0);
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementGenreReproductions("");
      Map<String, Integer> map0 = spotifUM0.getGenreReproductions();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap4);
      int int0 = spotifUM0.getPublicPlaylistSize();
      assertEquals(0, int0);
  }
}
