/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:22:13 GMT 2026
 */

package org.Model.Music;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Music.MusicMultimedia;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MusicMultimedia_ESTest extends MusicMultimedia_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      musicMultimedia0.setUrl((String) null);
      String string0 = musicMultimedia0.getUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      musicMultimedia0.setUrl("org.Model.Music.MusicMultimedia");
      String string0 = musicMultimedia0.getUrl();
      assertEquals("org.Model.Music.MusicMultimedia", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      musicMultimedia0.play();
      MusicMultimedia musicMultimedia1 = musicMultimedia0.clone();
      assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      musicMultimedia0.setReproductions((-1234));
      MusicMultimedia musicMultimedia1 = musicMultimedia0.clone();
      assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      musicMultimedia0.setDuration(1);
      MusicMultimedia musicMultimedia1 = musicMultimedia0.clone();
      assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = null;
      try {
        musicMultimedia0 = new MusicMultimedia((MusicMultimedia) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Music.Music", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      MusicMultimedia musicMultimedia1 = new MusicMultimedia(musicMultimedia0);
      assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      String string0 = musicMultimedia0.getUrl();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      MusicMultimedia musicMultimedia1 = new MusicMultimedia();
      musicMultimedia0.setUrl((String) null);
      assertFalse(musicMultimedia0.equals((Object)musicMultimedia1));
      
      musicMultimedia1.setUrl((String) null);
      boolean boolean0 = musicMultimedia1.equals(musicMultimedia0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      MusicMultimedia musicMultimedia1 = new MusicMultimedia();
      assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
      
      musicMultimedia1.setUrl((String) null);
      boolean boolean0 = musicMultimedia1.equals(musicMultimedia0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      MusicMultimedia musicMultimedia1 = new MusicMultimedia();
      boolean boolean0 = musicMultimedia0.equals(musicMultimedia1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      Object object0 = new Object();
      boolean boolean0 = musicMultimedia0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      boolean boolean0 = musicMultimedia0.equals(musicMultimedia0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia("\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", (-1), true, "\"0yZ*`bw,BF3nQjF11");
      MusicMultimedia musicMultimedia1 = new MusicMultimedia((String) null, "\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", "\"0yZ*`bw,BF3nQjF11", (-1), true, "\"0yZ*`bw,BF3nQjF11");
      boolean boolean0 = musicMultimedia1.equals(musicMultimedia0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia();
      String string0 = musicMultimedia0.toString();
      assertEquals("MusicaMultimedia{Nome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n, url=''}", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MusicMultimedia musicMultimedia0 = new MusicMultimedia("j", "", "j", "", "", "j", "", (-1), true, "");
      MusicMultimedia musicMultimedia1 = musicMultimedia0.clone();
      assertEquals("", musicMultimedia1.getUrl());
      assertTrue(musicMultimedia1.equals((Object)musicMultimedia0));
  }
}
