/*
 * This file was automatically generated by EvoSuite
 * Wed May 06 16:55:25 GMT 2026
 */

package org.Model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistRandom;
import org.Model.SpotifUM;
import org.Model.User.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockJapaneseDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SpotifUM_ESTest extends SpotifUM_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic("B?:ee-.<rD!c_aM6\"", "<y_c>", "<y_c>", "B?:ee-.<rD!c_aM6\"", "B?:ee-.<rD!c_aM6\"", "<y_c>", (String) null, (-2947), false, "\u2022 Electronic\n\u2022 Hino\n\u2022 Hip-Hop\n\u2022 Pop\n\u2022 Rock\n");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic((String) null, "H1", "H1", "N\u00E3o encontrado: ", "N\u00E3o encontrado: ", "N\u00E3o encontrado: ", (String) null, 2461, false, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      HashMap<String, Integer> hashMap5 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = new SpotifUM((Map<String, Music>) hashMap0, (Map<Integer, Playlist>) hashMap1, (Map<String, User>) hashMap2, (Map<String, Album>) hashMap3, (Map<String, Integer>) hashMap4, (Map<String, Integer>) hashMap5);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.setCurrentUserUsername("85Yi)!\"\"WyT");
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserUsername("85Yi)!\"\"WyT");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.setCurrentUserPassword("Genero Musical: ");
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.listCurrentUserPlaylists();
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.listAllMusicsInPlaylist((-2086126970));
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.hasLibrary();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      assertEquals("root", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<Integer, Playlist> map0 = spotifUM0.getPublicPlaylists();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      int int0 = spotifUM0.getPublicPlaylistSize();
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<String, Music> map0 = spotifUM0.getMusics();
      assertEquals(21, map0.size());
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      String string0 = spotifUM0.getCurrentUserPlanName();
      assertEquals("PremiumBase", string0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      User user1 = spotifUM0.getCurrentUser();
      assertEquals("root", user1.getPassword());
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<String, Album> map0 = spotifUM0.getAlbums();
      assertEquals(19, map0.size());
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.currentUserAccessToFavorites();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.canCurrentUserSkip();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.canCurrentUserChooseWhatToPlay();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", (User) null);
      spotifUM0.setUsers(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.userExists("David Guetta");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setPublicPlaylists((Map<Integer, Playlist>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setPlaylistAsPublic((-1929));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setMusics((Map<String, Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setArtistReproductions((Map<String, Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.incrementArtistReproductions((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.TreeMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.hasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, User> hashMap0 = new HashMap<String, User>(203, 203);
      hashMap0.put("My Mix", (User) null);
      spotifUM0.setUsers(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserWithMostPoints();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserPlaylistById((-1952257860));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      Integer integer0 = hashMap0.put("Discovery", (Integer) null);
      hashMap0.put("vo", integer0);
      spotifUM0.setArtistReproductions(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.getTopArtistName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.createGenrePlaylist((String) null, "\uD83C\uDFB5 [#000] Top Global                | Autor: Spotify        \n\uD83C\uDFB5 [#001] Rock Legends              | Autor: RockFM         \n\uD83C\uDFB5 [#002] Hip-Hop Nation            | Autor: HipHopTV       \n\uD83C\uDFB5 [#003] Electronic Vibes          | Autor: EDM.com        \n\uD83C\uDFB5 [#004] Throwback Hits            | Autor: OldiesFM       \n\uD83C\uDFB5 [#005] Portuguese Pride          | Autor: RTP            \n", (-2086126970));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o existem m\u00FAsicas desse g\u00E9nero.
         //
         assertThrownBy("org.Model.Playlist.PlaylistCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.changeCurrentUserName("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      SpotifUM spotifUM0 = null;
      try {
        spotifUM0 = new SpotifUM((SpotifUM) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.musicExists("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<Integer, Playlist> map0 = spotifUM0.getPublicPlaylists();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = spotifUM0.getCurrentUser();
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, User> map0 = spotifUM0.getUsers();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Music> map0 = spotifUM0.getMusics();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Album> map0 = spotifUM0.getAlbums();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Integer> map0 = spotifUM0.getGenreReproductions();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.equals(spotifUM0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      MockJapaneseDate mockJapaneseDate0 = new MockJapaneseDate();
      boolean boolean0 = spotifUM0.equals(mockJapaneseDate0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostReproductions();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", (User) null);
      spotifUM0.setUsers(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserWithMostReproductions();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      try { 
        spotifUM0.getUserWithMostReproductions(localDate0, localDate0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      try { 
        spotifUM0.getUserWithMostReproductions(localDate0, localDate0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostPlaylists();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("GRA1aog:)=`)S", "p", "", "");
      User user0 = spotifUM0.getUserWithMostPlaylists();
      assertEquals("", user0.getPassword());
      assertEquals("p", user0.getEmail());
      assertEquals("", user0.getAdress());
      assertEquals("GRA1aog:)=`)S", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getGenreWithMostReproductions();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem reprodu\u00E7\u00F5es na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementGenreReproductions("");
      String string0 = spotifUM0.getGenreWithMostReproductions();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostPoints();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getTopArtistName();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem artistas na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      hashMap0.put("Discovery", (Integer) null);
      spotifUM0.setArtistReproductions(hashMap0);
      String string0 = spotifUM0.getTopArtistName();
      assertEquals("Discovery - null\n", string0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.mostReproducedMusic();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem m\u00FAsicas na base de dados.
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Music music0 = spotifUM0.mostReproducedMusic();
      assertEquals("Synth", music0.getMusicalFigures());
      assertFalse(music0.isExplicit());
      assertEquals("Dua Lipa", music0.getInterpreter());
      assertEquals("Warner", music0.getPublisher());
      assertEquals("Future Nostalgia", music0.getAlbum());
      assertEquals("If you wanna run away with me, I know a galaxy\nAnd I can take you for a ride\nI had a premonition that we fell into a rhythm", music0.getLyrics());
      assertEquals(203, music0.getDuration());
      assertEquals("Pop", music0.getGenre());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllGenres();
      assertEquals("\u2022 Electronic\n\u2022 Hino\n\u2022 Hip-Hop\n\u2022 Pop\n\u2022 Rock\n", string0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllGenres();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<Integer, Playlist> hashMap0 = new HashMap<Integer, Playlist>();
      Integer integer0 = new Integer((-1160));
      hashMap0.put(integer0, (Playlist) null);
      spotifUM0.setPublicPlaylists(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.listPublicPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listPublicPlaylists();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.addPlaylistToCurrentUserLibrary((-169));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -169
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.addMusicToCurrentUserPlaylist((-1929), "H1");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: H1
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlaylistRandom playlistRandom0 = spotifUM0.getRandomPlaylist();
      assertEquals("Playlist Aleat\u00F3ria com 0 m\u00FAsicas.", playlistRandom0.getName());
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      PlaylistRandom playlistRandom0 = spotifUM0.getRandomPlaylist();
      assertEquals("Playlist Aleat\u00F3ria com 1 m\u00FAsicas.", playlistRandom0.getName());
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllAlbums();
      assertEquals("\uD83D\uDCC0 Future Nostalgia \u2014 Dua Lipa\n\uD83D\uDCC0 Scorpion \u2014 Drake\n\uD83D\uDCC0 Fine Line \u2014 Harry Styles\n\uD83D\uDCC0 ASTROWORLD \u2014 Travis Scott\n\uD83D\uDCC0 Discovery \u2014 Daft Punk\n\uD83D\uDCC0 DAMN. \u2014 Kendrick Lamar\n\uD83D\uDCC0 The Marshall Mathers LP 2 \u2014 Eminem\n\uD83D\uDCC0 Rick Roll \u2014 Rick Astley\n\uD83D\uDCC0 Divide \u2014 Ed Sheeran\n\uD83D\uDCC0 A Night at the Opera \u2014 Queen\n\uD83D\uDCC0 After Hours \u2014 The Weeknd\n\uD83D\uDCC0 Hotel California \u2014 Eagles\n\uD83D\uDCC0 Thriller \u2014 Michael Jackson\n\uD83D\uDCC0 Tanto Porto! \u2014 FC Porto\n\uD83D\uDCC0 Led Zeppelin IV \u2014 Led Zeppelin\n\uD83D\uDCC0 Starboy \u2014 The Weeknd\n\uD83D\uDCC0 Appetite for Destruction \u2014 Guns N' Roses\n\uD83D\uDCC0 Nothing but the Beat \u2014 David Guetta\n\uD83D\uDCC0 Nevermind \u2014 Nirvana\n", string0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllAlbums();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.addMusicToAlbum("X", (Music) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: X
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getAlbumByName("<5KH");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: <5KH
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.albumExists("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllMusics();
      assertEquals("\uD83C\uDFB6 Levitating \u2014 Dua Lipa\n\uD83C\uDFB6 Sweet Child O' Mine \u2014 Guns N' Roses\n\uD83C\uDFB6 Rap God \u2014 Eminem\n\uD83C\uDFB6 Bohemian Rhapsody \u2014 Queen\n\uD83C\uDFB6 Billie Jean \u2014 Michael Jackson\n\uD83C\uDFB6 Don't Start Now \u2014 Dua Lipa\n\uD83C\uDFB6 Blinding Lights \u2014 The Weeknd\n\uD83C\uDFB6 Hino do Futebol Clube do Porto \u2014 Maria Am\u00E9lia Canossa\n\uD83C\uDFB6 Shape of You \u2014 Ed Sheeran\n\uD83C\uDFB6 One More Time \u2014 Daft Punk\n\uD83C\uDFB6 Hotel California \u2014 Eagles\n\uD83C\uDFB6 Beat It \u2014 Michael Jackson\n\uD83C\uDFB6 Stairway to Heaven \u2014 Led Zeppelin\n\uD83C\uDFB6 Never Gonna Give You Up \u2014 Rick Astley\n\uD83C\uDFB6 God's Plan \u2014 Drake\n\uD83C\uDFB6 Titanium \u2014 David Guetta\n\uD83C\uDFB6 SICKO MODE \u2014 Travis Scott\n\uD83C\uDFB6 Starboy \u2014 The Weeknd\n\uD83C\uDFB6 HUMBLE. \u2014 Kendrick Lamar\n\uD83C\uDFB6 Watermelon Sugar \u2014 Harry Styles\n\uD83C\uDFB6 Smells Like Teen Spirit \u2014 Nirvana\n", string0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllMusics();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic("Duracao: ", "P}Eo+P'h^h4,)Z.d", "cNZbAu!I5E~56uh)", "P}Eo+P'h^h4,)Z.d", "cNZbAu!I5E~56uh)", "Duracao: ", "jI0@/kNj'&%!&q$v", 120, true, "jI0@/kNj'&%!&q$v");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic("\n  \uD83D\uDCCB Plano: ", "\n  \uD83D\uDCCB Plano: ", "They told him don't you ever come around here\nDon't wanna see your face, you better disappear\nThe fire's in their eyes and their words are really clear", "A6TMH+\"_7Ps", "nome='", "Duraca{: ", "nome='", (-1717986916), true, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getMusicByName("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.playMusic("2J");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 2J
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Integer integer0 = new Integer(0);
      try { 
        spotifUM0.removeMusicFromPlaylist("\uD83D\uDCC0 Future Nostalgia \u2014 Dua Lipa\n\uD83D\uDCC0 Scorpion \u2014 Drake\n\uD83D\uDCC0 Fine Line \u2014 Harry Styles\n\uD83D\uDCC0 ASTROWORLD \u2014 Travis Scott\n\uD83D\uDCC0 Discovery \u2014 Daft Punk\n\uD83D\uDCC0 DAMN. \u2014 Kendrick Lamar\n\uD83D\uDCC0 The Marshall Mathers LP 2 \u2014 Eminem\n\uD83D\uDCC0 Rick Roll \u2014 Rick Astley\n\uD83D\uDCC0 Divide \u2014 Ed Sheeran\n\uD83D\uDCC0 A Night at the Opera \u2014 Queen\n\uD83D\uDCC0 After Hours \u2014 The Weeknd\n\uD83D\uDCC0 Hotel California \u2014 Eagles\n\uD83D\uDCC0 Thriller \u2014 Michael Jackson\n\uD83D\uDCC0 Tanto Porto! \u2014 FC Porto\n\uD83D\uDCC0 Led Zeppelin IV \u2014 Led Zeppelin\n\uD83D\uDCC0 Starboy \u2014 The Weeknd\n\uD83D\uDCC0 Appetite for Destruction \u2014 Guns N' Roses\n\uD83D\uDCC0 Nothing but the Beat \u2014 David Guetta\n\uD83D\uDCC0 Nevermind \u2014 Nirvana\n", integer0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: \uD83D\uDCC0 Future Nostalgia \u2014 Dua Lipa
         // \uD83D\uDCC0 Scorpion \u2014 Drake
         // \uD83D\uDCC0 Fine Line \u2014 Harry Styles
         // \uD83D\uDCC0 ASTROWORLD \u2014 Travis Scott
         // \uD83D\uDCC0 Discovery \u2014 Daft Punk
         // \uD83D\uDCC0 DAMN. \u2014 Kendrick Lamar
         // \uD83D\uDCC0 The Marshall Mathers LP 2 \u2014 Eminem
         // \uD83D\uDCC0 Rick Roll \u2014 Rick Astley
         // \uD83D\uDCC0 Divide \u2014 Ed Sheeran
         // \uD83D\uDCC0 A Night at the Opera \u2014 Queen
         // \uD83D\uDCC0 After Hours \u2014 The Weeknd
         // \uD83D\uDCC0 Hotel California \u2014 Eagles
         // \uD83D\uDCC0 Thriller \u2014 Michael Jackson
         // \uD83D\uDCC0 Tanto Porto! \u2014 FC Porto
         // \uD83D\uDCC0 Led Zeppelin IV \u2014 Led Zeppelin
         // \uD83D\uDCC0 Starboy \u2014 The Weeknd
         // \uD83D\uDCC0 Appetite for Destruction \u2014 Guns N' Roses
         // \uD83D\uDCC0 Nothing but the Beat \u2014 David Guetta
         // \uD83D\uDCC0 Nevermind \u2014 Nirvana
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.userExists("<y_c>");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.userExists((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.authenticateUser("Shape of You", "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: Shape of You
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setUsers((Map<String, User>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // users is null
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.createFavoritesPlaylist((-169), true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      int int0 = spotifUM0.getPublicPlaylistSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addToCurrentUserMusicReproductions("Blinding Lights");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getPublicPlaylistById((-1245));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getUserPlaylistById((-380));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("1x$Txc]sF8", "1x$Txc]sF8", "1x$Txc]sF8", "1x$Txc]sF8");
      Map<String, User> map0 = spotifUM0.getUsers();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.canCurrentUserSkip();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.createGenrePlaylist("Artista: ", "Artista: ", (-899));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementArtistReproductions("<y_c>");
      Map<String, Integer> map0 = spotifUM0.getArtistReproductions();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      spotifUM0.setGenreReproductions(hashMap0);
      assertEquals(0, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserPassword("Genero Musical: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewAlbum("vOKqegumMJ?TW11 3=", "mb?RS;i+[=9<bN");
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getCurrentUserPlanName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addToCurrentUserPlaylist("David Guetta");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.listCurrentUserPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.toString();
      assertEquals("SpotifUM(...)", string0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      SpotifUM spotifUM1 = new SpotifUM(spotifUM0);
      assertEquals("SpotifUM(...)", spotifUM1.toString());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      spotifUM0.setMusics(hashMap0);
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.isPasswordCorrect("gY`.9iL(Te");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      spotifUM0.setAlbums(hashMap0);
      assertEquals(0, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addPlaylist("Yeah, they wishin' and wishin' and wishin' and wishin'\nThey wishin' on me, yuh\nI been movin' calm, don't start no trouble", "Cactus Jack");
      String string0 = spotifUM0.listPublicPlaylists();
      assertEquals("\uD83C\uDFB5 [#000] Yeah, they wishin' and wishin' and wishin' and wishin'\nThey wishin' on me, yuh\nI been movin' calm, don't start no trouble | Autor: Cactus Jack    \n", string0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.currentUserAccessToFavorites();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserEmail("LY!");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addPointsToCurrentUser();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Integer> map0 = spotifUM0.getArtistReproductions();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.canCurrentUserChooseWhatToPlay();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPoints();
      spotifUM0.setCurrentUser(user0);
      try { 
        spotifUM0.setPlaylistAsPublic((-21));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -21
         //
         assertThrownBy("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.incrementGenreReproductions((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.TreeMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      HashMap<Integer, Playlist> hashMap0 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap1 = new HashMap<String, User>();
      HashMap<String, Album> hashMap2 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap3 = new HashMap<String, Integer>();
      SpotifUM spotifUM0 = null;
      try {
        spotifUM0 = new SpotifUM((Map<String, Music>) null, (Map<Integer, Playlist>) hashMap0, (Map<String, User>) hashMap1, (Map<String, Album>) hashMap2, (Map<String, Integer>) hashMap3, (Map<String, Integer>) hashMap3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.SpotifUM", e);
      }
  }
}
