/*
 * This file was automatically generated by EvoSuite
 * Wed May 06 16:54:01 GMT 2026
 */

package org.Model.Music;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Music.Music;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Music_ESTest extends Music_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Music music0 = new Music("", "A_", "", "A_", "Explicita: ", "A_", "", (-2339), false);
      music0.play();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Music music0 = new Music("Linhas Musicais: ", "Linhas Musicais: ", "Album: ", "Linhas Musicais: ", "-M0,`j/{t=Tb%_USqb", "-M0,`j/{t=Tb%_USqb", "Album: ", 213, true);
      boolean boolean0 = music0.isExplicit();
      assertEquals("Linhas Musicais: ", music0.getInterpreter());
      assertEquals("Album: ", music0.getAlbum());
      assertEquals("-M0,`j/{t=Tb%_USqb", music0.getMusicalFigures());
      assertEquals("Linhas Musicais: ", music0.getName());
      assertEquals("Album: ", music0.getPublisher());
      assertEquals("Linhas Musicais: ", music0.getLyrics());
      assertEquals("-M0,`j/{t=Tb%_USqb", music0.getGenre());
      assertEquals(213, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Music music0 = new Music();
      music0.play();
      int int0 = music0.getReproductions();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Music music0 = new Music();
      music0.setReproductions((-2204));
      int int0 = music0.getReproductions();
      assertEquals((-2204), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Music music0 = new Music("", (String) null, (String) null, "", "", "Album: ", "Album: ", 3711, true);
      String string0 = music0.getPublisher();
      assertEquals(0, music0.getReproductions());
      assertEquals("Album: ", music0.getAlbum());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getLyrics());
      assertEquals("", music0.getName());
      assertNull(string0);
      assertEquals(3711, music0.getDuration());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("Album: ", music0.getGenre());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Music music0 = new Music("^Eq!S'8>L*8", "^Eq!S'8>L*8", "^Eq!S'8>L*8", "^Eq!S'8>L*8", "^Eq!S'8>L*8", "^Eq!S'8>L*8", "", 0, true);
      String string0 = music0.getPublisher();
      assertEquals("^Eq!S'8>L*8", music0.getName());
      assertEquals("", music0.getAlbum());
      assertEquals(0, music0.getDuration());
      assertEquals("^Eq!S'8>L*8", music0.getInterpreter());
      assertEquals("^Eq!S'8>L*8", music0.getMusicalFigures());
      assertTrue(music0.isExplicit());
      assertEquals("^Eq!S'8>L*8", music0.getLyrics());
      assertEquals(0, music0.getReproductions());
      assertEquals("^Eq!S'8>L*8", string0);
      assertEquals("^Eq!S'8>L*8", music0.getGenre());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Music music0 = new Music();
      music0.setName((String) null);
      music0.getName();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Music music0 = new Music();
      music0.getName();
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Music music0 = new Music("u,", (String) null, "Album: ", "Album: ", (String) null, "7~ES", "7~ES", (-1990), true);
      String string0 = music0.getMusicalFigures();
      assertEquals("Album: ", music0.getLyrics());
      assertEquals("7~ES", music0.getAlbum());
      assertEquals(-1990, music0.getDuration());
      assertNull(string0);
      assertEquals(0, music0.getReproductions());
      assertTrue(music0.isExplicit());
      assertEquals("Album: ", music0.getPublisher());
      assertEquals("u,", music0.getName());
      assertEquals("7~ES", music0.getGenre());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Music music0 = new Music();
      music0.getMusicalFigures();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Music music0 = new Music();
      music0.setLyrics((String) null);
      music0.getLyrics();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Music music0 = new Music();
      music0.getLyrics();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, "r*jD7mP%/hb", "r*jD7mP%/hb", (String) null, "", (String) null, 0, false);
      String string0 = music0.getInterpreter();
      assertNull(string0);
      assertEquals("r*jD7mP%/hb", music0.getLyrics());
      assertEquals("r*jD7mP%/hb", music0.getPublisher());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals("", music0.getGenre());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Music music0 = new Music("Linhas Musicais: ", "Linhas Musicais: ", "Album: ", "Linhas Musicais: ", "-M0,`j/{t=Tb%_USqb", "-M0,`j/{t=Tb%_USqb", "Album: ", 213, true);
      String string0 = music0.getInterpreter();
      assertEquals("-M0,`j/{t=Tb%_USqb", music0.getGenre());
      assertEquals(213, music0.getDuration());
      assertEquals("Linhas Musicais: ", music0.getLyrics());
      assertTrue(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals("-M0,`j/{t=Tb%_USqb", music0.getMusicalFigures());
      assertEquals("Linhas Musicais: ", music0.getName());
      assertEquals("Album: ", music0.getPublisher());
      assertEquals("Linhas Musicais: ", string0);
      assertEquals("Album: ", music0.getAlbum());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (-1533), false);
      music0.setGenre("");
      music0.getGenre();
      assertFalse(music0.isExplicit());
      assertEquals(-1533, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Music music0 = new Music();
      assertEquals(0, music0.getDuration());
      
      music0.setDuration(1);
      int int0 = music0.getDuration();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Music music0 = new Music();
      music0.setDuration((-493));
      int int0 = music0.getDuration();
      assertEquals((-493), int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "O@rz3j!L98VbKa]", "", 0, true);
      assertEquals("", music0.getAlbum());
      
      music0.setAlbum((String) null);
      music0.getAlbum();
      assertEquals("O@rz3j!L98VbKa]", music0.getGenre());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getPublisher());
      assertEquals("", music0.getName());
      assertEquals(0, music0.getDuration());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getLyrics());
      assertEquals("", music0.getInterpreter());
      assertEquals("", music0.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Music music0 = new Music();
      music0.setAlbum("j,!AC_fa_5H}y7u>; W");
      music0.getAlbum();
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Music music0 = new Music();
      music0.play();
      music0.clone();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Music music0 = new Music("", (String) null, (String) null, "", "", "Album: ", "Album: ", 3711, true);
      Music music1 = music0.clone();
      assertEquals(3711, music1.getDuration());
      assertEquals("", music1.getLyrics());
      assertEquals(3711, music0.getDuration());
      assertTrue(music1.equals((Object)music0));
      assertEquals("Album: ", music1.getGenre());
      assertEquals("", music1.getMusicalFigures());
      assertEquals(0, music1.getReproductions());
      assertTrue(music1.isExplicit());
      assertEquals("", music1.getName());
      assertEquals("Album: ", music1.getAlbum());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Music music0 = new Music();
      music0.setDuration((-876));
      music0.clone();
      assertEquals(-876, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Music music0 = null;
      try {
        music0 = new Music((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Music.Music", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Music music0 = new Music("Linhas Musicais: ", "Linhas Musicais: ", "Album: ", "Linhas Musicais: ", "-M0,`j/{t=Tb%_USqb", "-M0,`j/{t=Tb%_USqb", "Album: ", 213, true);
      String string0 = music0.getMusicalFigures();
      assertEquals("Linhas Musicais: ", music0.getInterpreter());
      assertEquals("-M0,`j/{t=Tb%_USqb", string0);
      assertEquals("Album: ", music0.getAlbum());
      assertEquals("Album: ", music0.getPublisher());
      assertEquals(213, music0.getDuration());
      assertEquals("Linhas Musicais: ", music0.getLyrics());
      assertTrue(music0.isExplicit());
      assertEquals("-M0,`j/{t=Tb%_USqb", music0.getGenre());
      assertEquals(0, music0.getReproductions());
      assertEquals("Linhas Musicais: ", music0.getName());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "O@rz3j!L98VbKa]", "", 0, true);
      String string0 = music0.getGenre();
      assertEquals("", music0.getAlbum());
      assertEquals("", music0.getPublisher());
      assertEquals(0, music0.getDuration());
      assertEquals("", music0.getLyrics());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getName());
      assertEquals("", music0.getInterpreter());
      assertEquals(0, music0.getReproductions());
      assertEquals("O@rz3j!L98VbKa]", string0);
      assertEquals("", music0.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Music music0 = new Music("", "A_", "", "A_", "Explicita: ", "A_", "", (-2339), false);
      Music music1 = new Music(music0);
      assertEquals("A_", music1.getInterpreter());
      assertEquals("", music1.getName());
      assertEquals("", music1.getPublisher());
      assertEquals(0, music1.getReproductions());
      assertEquals("Explicita: ", music1.getMusicalFigures());
      assertEquals(-2339, music1.getDuration());
      assertEquals("A_", music1.getGenre());
      assertEquals("A_", music1.getLyrics());
      assertEquals("", music1.getAlbum());
      assertFalse(music1.isExplicit());
      assertEquals(-2339, music0.getDuration());
      assertTrue(music1.equals((Object)music0));
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "", (-399), true);
      int int0 = music0.getReproductions();
      assertEquals(0, int0);
      assertEquals(-399, music0.getDuration());
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "O@rz3j!L98VbKa]", "", 0, true);
      String string0 = music0.getAlbum();
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getPublisher());
      assertEquals("", music0.getMusicalFigures());
      assertEquals(0, music0.getDuration());
      assertEquals("", string0);
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getName());
      assertEquals("", music0.getInterpreter());
      assertEquals("O@rz3j!L98VbKa]", music0.getGenre());
      assertEquals("", music0.getLyrics());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Music music0 = new Music("6.4!I:fzskn&3*?bpgK", "6.4!I:fzskn&3*?bpgK", "@r'DLa", "", "6.4!I:fzskn&3*?bpgK", "6.4!I:fzskn&3*?bpgK", "Os?<141", (-345), false);
      String string0 = music0.getName();
      assertEquals("6.4!I:fzskn&3*?bpgK", music0.getInterpreter());
      assertEquals("Os?<141", music0.getAlbum());
      assertEquals(-345, music0.getDuration());
      assertEquals("6.4!I:fzskn&3*?bpgK", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getLyrics());
      assertEquals("6.4!I:fzskn&3*?bpgK", string0);
      assertFalse(music0.isExplicit());
      assertEquals("@r'DLa", music0.getPublisher());
      assertEquals("6.4!I:fzskn&3*?bpgK", music0.getGenre());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Music music0 = new Music("", "", (String) null, "Y", "", "Y", "Qz9`@", 161, true);
      String string0 = music0.getLyrics();
      assertEquals(161, music0.getDuration());
      assertEquals("Y", music0.getGenre());
      assertEquals("", music0.getInterpreter());
      assertTrue(music0.isExplicit());
      assertEquals("Qz9`@", music0.getAlbum());
      assertEquals("", music0.getName());
      assertNotNull(string0);
      assertEquals("Y", string0);
      assertEquals("", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Music music0 = new Music("", "A_", "", "A_", "Explicita: ", "A_", "", (-2339), false);
      boolean boolean0 = music0.isExplicit();
      assertEquals("", music0.getAlbum());
      assertEquals("A_", music0.getGenre());
      assertEquals(-2339, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertEquals("A_", music0.getLyrics());
      assertEquals("", music0.getPublisher());
      assertEquals("", music0.getName());
      assertEquals("A_", music0.getInterpreter());
      assertFalse(boolean0);
      assertEquals("Explicita: ", music0.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "O@rz3j!L98VbKa]", "", 0, true);
      String string0 = music0.getInterpreter();
      assertEquals("", music0.getAlbum());
      assertEquals("", music0.getPublisher());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
      assertEquals("", string0);
      assertEquals("", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals("O@rz3j!L98VbKa]", music0.getGenre());
      assertEquals("", music0.getLyrics());
      assertEquals("", music0.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Music music0 = new Music();
      music0.getPublisher();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Music music0 = new Music();
      int int0 = music0.getDuration();
      assertEquals(0, int0);
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Music music0 = new Music();
      Music music1 = music0.clone();
      music0.equals(music1);
      assertTrue(music1.equals((Object)music0));
      assertFalse(music1.isExplicit());
      assertEquals(0, music1.getDuration());
      assertEquals(0, music1.getReproductions());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (-1533), false);
      Integer integer0 = new Integer((-1533));
      boolean boolean0 = music0.equals(integer0);
      assertEquals(0, music0.getReproductions());
      assertEquals(-1533, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Music music0 = new Music();
      boolean boolean0 = music0.equals(music0);
      assertEquals(0, music0.getDuration());
      assertTrue(boolean0);
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "O@rz3j!L98VbKa]", "", 0, true);
      String string0 = music0.toString();
      assertEquals("Nome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: O@rz3j!L98VbKa]\nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Sim\n", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, "r*jD7mP%/hb", "r*jD7mP%/hb", (String) null, "", (String) null, 0, false);
      String string0 = music0.toString();
      assertEquals("Nome: null\nInterprete: null\nEditora: r*jD7mP%/hb\nLetra: r*jD7mP%/hb\nLinhas Musicais: null\nGenero Musical: \nAlbum: null\nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n", string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Music music0 = new Music();
      music0.setReproductions((-676));
      music0.clone();
      assertEquals(-676, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Music music0 = new Music();
      assertFalse(music0.isExplicit());
      
      music0.setExplicit(true);
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Music music0 = new Music();
      music0.setMusicalFigures("l{2P");
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Music music0 = new Music();
      music0.setGenre((String) null);
      music0.getGenre();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (-1533), false);
      music0.play();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Music music0 = new Music();
      music0.setPublisher("7KIhv<");
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Music music0 = new Music();
      music0.setName((String) null);
      Music music1 = music0.clone();
      boolean boolean0 = music0.equals(music1);
      assertTrue(boolean0);
      assertFalse(music1.isExplicit());
      assertEquals(0, music1.getReproductions());
      assertEquals(0, music1.getDuration());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Music music0 = new Music();
      Music music1 = music0.clone();
      assertTrue(music1.equals((Object)music0));
      
      music1.setName((String) null);
      boolean boolean0 = music1.equals(music0);
      assertFalse(music1.equals((Object)music0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Music music0 = new Music();
      music0.setInterpreter((String) null);
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }
}
