/*
 * This file was automatically generated by EvoSuite
 * Wed May 06 16:29:39 GMT 2026
 */

package org.Model.Music;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Music.Music;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Music_ESTest extends Music_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "", "", 0, true);
      Music music1 = new Music(music0);
      assertEquals(0, music1.getDuration());
      assertEquals(0, music1.getReproductions());
      assertTrue(music1.isExplicit());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Music music0 = new Music("7:\"+~c;\"q", "_$S}_xG7%{`w{0Bew-<", "_$S}_xG7%{`w{0Bew-<", "_$S}_xG7%{`w{0Bew-<", "7:\"+~c;\"q", "_$S}_xG7%{`w{0Bew-<", "", 2053, false);
      music0.play();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Music music0 = new Music("", ">X^=M", (String) null, "", "/d>u", "", "}'2lpUw", (-1), true);
      music0.play();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "", "", 0, true);
      music0.play();
      int int0 = music0.getReproductions();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Music music0 = new Music();
      music0.setReproductions((-612));
      int int0 = music0.getReproductions();
      assertEquals((-612), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Music music0 = new Music("o&taU[5Enw|DO<*\"k4", "o&taU[5Enw|DO<*\"k4", (String) null, "", (String) null, (String) null, "o&taU[5Enw|DO<*\"k4", (-1231), false);
      String string0 = music0.getPublisher();
      assertEquals("o&taU[5Enw|DO<*\"k4", music0.getName());
      assertNull(string0);
      assertEquals(-1231, music0.getDuration());
      assertEquals("", music0.getLyrics());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals("o&taU[5Enw|DO<*\"k4", music0.getAlbum());
      assertEquals("o&taU[5Enw|DO<*\"k4", music0.getInterpreter());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Music music0 = new Music("%", "%", "%", "lQX", "lQX", (String) null, "", 4988, true);
      String string0 = music0.getPublisher();
      assertTrue(music0.isExplicit());
      assertEquals("lQX", music0.getLyrics());
      assertEquals("%", string0);
      assertNotNull(string0);
      assertEquals("%", music0.getInterpreter());
      assertEquals("%", music0.getName());
      assertEquals(0, music0.getReproductions());
      assertEquals("lQX", music0.getMusicalFigures());
      assertEquals("", music0.getAlbum());
      assertEquals(4988, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "", "", 0, true);
      String string0 = music0.getName();
      assertEquals(0, music0.getDuration());
      assertNull(string0);
      assertTrue(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Music music0 = new Music("R,8%", "R,8%", "", ".`8oGYc(C36Nx'gOQ:B", "", "N>z", "R,8%", (-1), true);
      String string0 = music0.getName();
      assertEquals(".`8oGYc(C36Nx'gOQ:B", music0.getLyrics());
      assertEquals("", music0.getPublisher());
      assertTrue(music0.isExplicit());
      assertEquals("R,8%", music0.getInterpreter());
      assertEquals("N>z", music0.getGenre());
      assertEquals("R,8%", string0);
      assertEquals(-1, music0.getDuration());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("R,8%", music0.getAlbum());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "jyc+G*+=NXvNlDDj", "jyc+G*+=NXvNlDDj", 0, true);
      String string0 = music0.getMusicalFigures();
      assertEquals(0, music0.getReproductions());
      assertNull(string0);
      assertEquals(0, music0.getDuration());
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Music music0 = new Music();
      music0.getMusicalFigures();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "jyc+G*+=NXvNlDDj", "jyc+G*+=NXvNlDDj", 0, true);
      music0.setLyrics("Letra: ");
      music0.getLyrics();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Music music0 = new Music();
      music0.getLyrics();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "", "", 0, true);
      music0.setInterpreter("Nao");
      music0.getInterpreter();
      assertEquals(0, music0.getReproductions());
      assertTrue(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Music music0 = new Music();
      music0.getInterpreter();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Music music0 = new Music("o&taU[5Enw|DO<*\"k4", "o&taU[5Enw|DO<*\"k4", (String) null, "", (String) null, (String) null, "o&taU[5Enw|DO<*\"k4", (-1231), false);
      String string0 = music0.getGenre();
      assertEquals("", music0.getLyrics());
      assertFalse(music0.isExplicit());
      assertEquals(-1231, music0.getDuration());
      assertEquals("o&taU[5Enw|DO<*\"k4", music0.getName());
      assertEquals("o&taU[5Enw|DO<*\"k4", music0.getInterpreter());
      assertNull(string0);
      assertEquals(0, music0.getReproductions());
      assertEquals("o&taU[5Enw|DO<*\"k4", music0.getAlbum());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Music music0 = new Music();
      music0.getGenre();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Music music0 = new Music();
      int int0 = music0.getDuration();
      assertEquals(0, int0);
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Music music0 = new Music();
      music0.setDuration(292);
      int int0 = music0.getDuration();
      assertEquals(292, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Music music0 = new Music("", ">X^=M", (String) null, "", "/d>u", "", "}'2lpUw", (-1), true);
      assertEquals("}'2lpUw", music0.getAlbum());
      
      music0.setAlbum((String) null);
      music0.getAlbum();
      assertEquals("", music0.getGenre());
      assertEquals("", music0.getLyrics());
      assertEquals(">X^=M", music0.getInterpreter());
      assertEquals("", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals("/d>u", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
      assertEquals(-1, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Music music0 = new Music();
      music0.getAlbum();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Music music0 = new Music();
      music0.setReproductions((-81));
      music0.clone();
      assertEquals(-81, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Music music0 = new Music("", ">X^=M", (String) null, "", "/d>u", "", "}'2lpUw", (-1), true);
      Music music1 = music0.clone();
      assertEquals(-1, music1.getDuration());
      assertEquals("", music1.getLyrics());
      assertEquals("", music1.getGenre());
      assertEquals(">X^=M", music1.getInterpreter());
      assertEquals(0, music1.getReproductions());
      assertTrue(music1.isExplicit());
      assertEquals("", music1.getName());
      assertTrue(music1.equals((Object)music0));
      assertEquals("/d>u", music1.getMusicalFigures());
      assertEquals(-1, music0.getDuration());
      assertEquals("}'2lpUw", music1.getAlbum());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Music music0 = new Music("", ">X^=M", (String) null, "", "/d>u", "", "}'2lpUw", (-1), true);
      String string0 = music0.getMusicalFigures();
      assertEquals(-1, music0.getDuration());
      assertEquals("", music0.getLyrics());
      assertEquals("", music0.getGenre());
      assertEquals("/d>u", string0);
      assertNotNull(string0);
      assertEquals("}'2lpUw", music0.getAlbum());
      assertEquals("", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals(">X^=M", music0.getInterpreter());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Music music0 = new Music("7:\"+~c;\"q", "_$S}_xG7%{`w{0Bew-<", "_$S}_xG7%{`w{0Bew-<", "_$S}_xG7%{`w{0Bew-<", "7:\"+~c;\"q", "_$S}_xG7%{`w{0Bew-<", "", 2053, false);
      String string0 = music0.getGenre();
      assertEquals("_$S}_xG7%{`w{0Bew-<", music0.getLyrics());
      assertEquals(0, music0.getReproductions());
      assertEquals("7:\"+~c;\"q", music0.getMusicalFigures());
      assertFalse(music0.isExplicit());
      assertEquals("", music0.getAlbum());
      assertEquals("7:\"+~c;\"q", music0.getName());
      assertEquals("_$S}_xG7%{`w{0Bew-<", string0);
      assertEquals("_$S}_xG7%{`w{0Bew-<", music0.getPublisher());
      assertEquals("_$S}_xG7%{`w{0Bew-<", music0.getInterpreter());
      assertEquals(2053, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Music music0 = null;
      try {
        music0 = new Music((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Music.Music", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "", "", 0, true);
      int int0 = music0.getReproductions();
      assertEquals(0, int0);
      assertTrue(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Music music0 = new Music("", ">X^=M", (String) null, "", "/d>u", "", "}'2lpUw", (-1), true);
      String string0 = music0.getAlbum();
      assertEquals("/d>u", music0.getMusicalFigures());
      assertEquals(">X^=M", music0.getInterpreter());
      assertEquals(0, music0.getReproductions());
      assertEquals("}'2lpUw", string0);
      assertEquals("", music0.getLyrics());
      assertEquals("", music0.getName());
      assertEquals(-1, music0.getDuration());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getGenre());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Music music0 = new Music("", "org.Model.Music.Music", "", "", "", "Linhas Musicais: ", "Linhas Musicais: ", (-5422), true);
      String string0 = music0.getName();
      assertEquals("Linhas Musicais: ", music0.getGenre());
      assertEquals("", music0.getPublisher());
      assertEquals("Linhas Musicais: ", music0.getAlbum());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
      assertEquals("org.Model.Music.Music", music0.getInterpreter());
      assertEquals(-5422, music0.getDuration());
      assertEquals("", music0.getLyrics());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "", "", 0, true);
      String string0 = music0.getLyrics();
      assertTrue(music0.isExplicit());
      assertNull(string0);
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Music music0 = new Music();
      boolean boolean0 = music0.isExplicit();
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "", "", 0, true);
      String string0 = music0.getInterpreter();
      assertEquals(0, music0.getDuration());
      assertTrue(music0.isExplicit());
      assertNull(string0);
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "", (-1), true);
      music0.getPublisher();
      assertEquals(0, music0.getReproductions());
      assertEquals(-1, music0.getDuration());
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Music music0 = new Music("", "org.Model.Music.Music", "", "", "", "Linhas Musicais: ", "Linhas Musicais: ", (-5422), true);
      int int0 = music0.getDuration();
      assertEquals((-5422), int0);
      assertEquals("", music0.getLyrics());
      assertEquals("org.Model.Music.Music", music0.getInterpreter());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("", music0.getPublisher());
      assertTrue(music0.isExplicit());
      assertEquals("Linhas Musicais: ", music0.getGenre());
      assertEquals("Linhas Musicais: ", music0.getAlbum());
      assertEquals("", music0.getName());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Music music0 = new Music();
      Music music1 = new Music();
      music0.setName((String) null);
      assertFalse(music0.equals((Object)music1));
      
      music1.setName((String) null);
      boolean boolean0 = music0.equals(music1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Music music0 = new Music();
      Music music1 = new Music();
      assertTrue(music1.equals((Object)music0));
      
      music0.setName((String) null);
      boolean boolean0 = music0.equals(music1);
      assertFalse(boolean0);
      assertEquals(0, music1.getDuration());
      assertFalse(music1.isExplicit());
      assertEquals(0, music1.getReproductions());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Music music0 = new Music();
      Music music1 = music0.clone();
      boolean boolean0 = music1.equals(music0);
      assertTrue(boolean0);
      assertFalse(music1.isExplicit());
      assertEquals(0, music1.getReproductions());
      assertEquals(0, music1.getDuration());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Music music0 = new Music();
      boolean boolean0 = music0.equals(music0);
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Music music0 = new Music("=GR~i@+O[q.\u0002U7", "Album: ", "", "Dw`]AOdogsmhw#=", "=GR~i@+O[q.\u0002U7", "=GR~i@+O[q.\u0002U7", "Album: ", 0, false);
      boolean boolean0 = music0.equals("");
      assertEquals("", music0.getPublisher());
      assertEquals(0, music0.getReproductions());
      assertEquals("Album: ", music0.getInterpreter());
      assertEquals("Album: ", music0.getAlbum());
      assertEquals("=GR~i@+O[q.\u0002U7", music0.getGenre());
      assertFalse(music0.isExplicit());
      assertFalse(boolean0);
      assertEquals("Dw`]AOdogsmhw#=", music0.getLyrics());
      assertEquals("=GR~i@+O[q.\u0002U7", music0.getName());
      assertEquals(0, music0.getDuration());
      assertEquals("=GR~i@+O[q.\u0002U7", music0.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "", "", 0, true);
      String string0 = music0.toString();
      assertEquals("Nome: null\nInterprete: null\nEditora: null\nLetra: null\nLinhas Musicais: null\nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Sim\n", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Music music0 = new Music();
      String string0 = music0.toString();
      assertEquals("Nome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Music music0 = new Music();
      assertFalse(music0.isExplicit());
      
      music0.setExplicit(true);
      boolean boolean0 = music0.isExplicit();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "", "", 0, true);
      music0.play();
      music0.clone();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Music music0 = new Music("", "org.Model.Music.Music", "", "", "", "Linhas Musicais: ", "Linhas Musicais: ", (-5422), true);
      assertEquals("", music0.getMusicalFigures());
      
      music0.setMusicalFigures("Explicita: ");
      assertEquals("", music0.getPublisher());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "", "", 0, true);
      music0.setGenre("qdG");
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Music music0 = new Music();
      music0.setPublisher("Album: ");
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Music music0 = new Music("7:\"+~c;\"q", "_$S}_xG7%{`w{0Bew-<", "_$S}_xG7%{`w{0Bew-<", "_$S}_xG7%{`w{0Bew-<", "7:\"+~c;\"q", "_$S}_xG7%{`w{0Bew-<", "", 2053, false);
      Music music1 = music0.clone();
      assertEquals(2053, music1.getDuration());
      assertEquals("7:\"+~c;\"q", music1.getMusicalFigures());
      assertEquals(0, music1.getReproductions());
      assertTrue(music1.equals((Object)music0));
      assertEquals(2053, music0.getDuration());
      assertEquals("_$S}_xG7%{`w{0Bew-<", music1.getInterpreter());
      assertFalse(music1.isExplicit());
      assertEquals("_$S}_xG7%{`w{0Bew-<", music1.getPublisher());
      assertEquals("7:\"+~c;\"q", music1.getName());
      assertEquals("_$S}_xG7%{`w{0Bew-<", music1.getLyrics());
      assertEquals("", music1.getAlbum());
      assertEquals("_$S}_xG7%{`w{0Bew-<", music1.getGenre());
  }
}
