/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 14 13:25:03 GMT 2026
 */

package org.Model.Music;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Music.Music;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Music_ESTest extends Music_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, ".>x#q09%rd!'>0$yF", (String) null, (-1), false);
      music0.play();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "M*apMv\n}", "", "", (-49), true);
      boolean boolean0 = music0.isExplicit();
      assertEquals(-49, music0.getDuration());
      assertEquals("M*apMv\n}", music0.getMusicalFigures());
      assertEquals("", music0.getName());
      assertEquals("", music0.getLyrics());
      assertEquals("", music0.getGenre());
      assertEquals("", music0.getPublisher());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getInterpreter());
      assertTrue(boolean0);
      assertEquals("", music0.getAlbum());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Music music0 = new Music();
      music0.play();
      int int0 = music0.getReproductions();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Music music0 = new Music();
      music0.setReproductions((-1806));
      int int0 = music0.getReproductions();
      assertEquals((-1806), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, ".>x#q09%rd!'>0$yF", (String) null, (-1), false);
      String string0 = music0.getPublisher();
      assertNull(string0);
      assertEquals(-1, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Music music0 = new Music();
      music0.getPublisher();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, "org.Model.Music.Music", (String) null, (String) null, 1, false);
      String string0 = music0.getName();
      assertEquals(0, music0.getReproductions());
      assertEquals(1, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Music music0 = new Music();
      music0.setName("Genero Musical: ");
      music0.getName();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Music music0 = new Music();
      music0.getMusicalFigures();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, "org.Model.Music.Music", (String) null, (String) null, 1, false);
      String string0 = music0.getLyrics();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertNull(string0);
      assertEquals(1, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Music music0 = new Music("9TMQ>Zd", "9TMQ>Zd", "9TMQ>Zd", "9TMQ>Zd", "9TMQ>Zd", "9TMQ>Zd", "9TMQ>Zd", 1844, false);
      music0.getLyrics();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(1844, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, "org.Model.Music.Music", (String) null, (String) null, 1, false);
      String string0 = music0.getInterpreter();
      assertEquals(1, music0.getDuration());
      assertNull(string0);
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Music music0 = new Music();
      music0.getInterpreter();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Music music0 = new Music((String) null, "z)J:(L62", "Genero Musical: ", "", "?;", (String) null, "", 5734, false);
      String string0 = music0.getGenre();
      assertEquals("?;", music0.getMusicalFigures());
      assertEquals("z)J:(L62", music0.getInterpreter());
      assertEquals("", music0.getLyrics());
      assertNull(string0);
      assertEquals("", music0.getAlbum());
      assertEquals(0, music0.getReproductions());
      assertEquals(5734, music0.getDuration());
      assertEquals("Genero Musical: ", music0.getPublisher());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Music music0 = new Music();
      music0.setGenre("pBj*][!>Y0Z(V%");
      music0.getGenre();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Music music0 = new Music();
      int int0 = music0.getDuration();
      assertEquals(0, int0);
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Music music0 = new Music("", "", "", "Explicita: ", "Explicita: ", "%UP(2qdWiN2Dc", "%UP(2qdWiN2Dc", (-2117), true);
      int int0 = music0.getDuration();
      assertEquals("Explicita: ", music0.getLyrics());
      assertEquals(0, music0.getReproductions());
      assertEquals("Explicita: ", music0.getMusicalFigures());
      assertEquals("%UP(2qdWiN2Dc", music0.getGenre());
      assertEquals("", music0.getInterpreter());
      assertEquals((-2117), int0);
      assertEquals("%UP(2qdWiN2Dc", music0.getAlbum());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getName());
      assertEquals("", music0.getPublisher());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, "org.Model.Music.Music", (String) null, (String) null, 1, false);
      String string0 = music0.getAlbum();
      assertEquals(1, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Music music0 = new Music();
      music0.getAlbum();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Music music0 = new Music();
      music0.setReproductions((-2272));
      music0.clone();
      assertEquals(-2272, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Music music0 = new Music();
      Music music1 = music0.clone();
      assertEquals(0, music1.getDuration());
      assertEquals(0, music1.getReproductions());
      assertTrue(music1.equals((Object)music0));
      assertFalse(music1.isExplicit());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Music music0 = null;
      try {
        music0 = new Music((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Music.Music", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Music music0 = new Music(")\"6i5o BR'^MRV", "JT_RYU|]'lE8", ")\"6i5o BR'^MRV", ")\"6i5o BR'^MRV", ")\"6i5o BR'^MRV", "", ")\"6i5o BR'^MRV", 0, false);
      String string0 = music0.getMusicalFigures();
      assertEquals("", music0.getGenre());
      assertEquals(")\"6i5o BR'^MRV", music0.getPublisher());
      assertEquals(0, music0.getDuration());
      assertEquals(")\"6i5o BR'^MRV", music0.getName());
      assertEquals(0, music0.getReproductions());
      assertEquals(")\"6i5o BR'^MRV", music0.getLyrics());
      assertEquals(")\"6i5o BR'^MRV", music0.getAlbum());
      assertEquals("JT_RYU|]'lE8", music0.getInterpreter());
      assertEquals(")\"6i5o BR'^MRV", string0);
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Music music0 = new Music();
      music0.getGenre();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Music music0 = new Music("xU}_dz+L~w,M", "xU}_dz+L~w,M", "fhd`!W#v]<|ruHA'Q", "fhd`!W#v]<|ruHA'Q", "", (String) null, "", 1, true);
      Music music1 = new Music(music0);
      assertEquals("", music1.getAlbum());
      assertEquals("fhd`!W#v]<|ruHA'Q", music1.getPublisher());
      assertEquals(1, music1.getDuration());
      assertEquals("xU}_dz+L~w,M", music1.getInterpreter());
      assertTrue(music1.equals((Object)music0));
      assertTrue(music1.isExplicit());
      assertEquals("xU}_dz+L~w,M", music1.getName());
      assertEquals(1, music0.getDuration());
      assertEquals("fhd`!W#v]<|ruHA'Q", music1.getLyrics());
      assertEquals(0, music1.getReproductions());
      assertEquals("", music1.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Music music0 = new Music();
      int int0 = music0.getReproductions();
      assertFalse(music0.isExplicit());
      assertEquals(0, int0);
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Music music0 = new Music(")\"6i5o BR'^MRV", "JT_RYU|]'lE8", ")\"6i5o BR'^MRV", ")\"6i5o BR'^MRV", ")\"6i5o BR'^MRV", "", ")\"6i5o BR'^MRV", 0, false);
      String string0 = music0.getAlbum();
      assertEquals(")\"6i5o BR'^MRV", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
      assertEquals(")\"6i5o BR'^MRV", music0.getName());
      assertEquals(")\"6i5o BR'^MRV", music0.getLyrics());
      assertEquals("", music0.getGenre());
      assertEquals(0, music0.getDuration());
      assertEquals(")\"6i5o BR'^MRV", string0);
      assertEquals("JT_RYU|]'lE8", music0.getInterpreter());
      assertEquals(")\"6i5o BR'^MRV", music0.getPublisher());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Music music0 = new Music();
      music0.getName();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Music music0 = new Music();
      music0.getLyrics();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Music music0 = new Music();
      boolean boolean0 = music0.isExplicit();
      assertFalse(boolean0);
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Music music0 = new Music("xU}_dz+L~w,M", "xU}_dz+L~w,M", "fhd`!W#v]<|ruHA'Q", "fhd`!W#v]<|ruHA'Q", "", (String) null, "", 1, true);
      String string0 = music0.getInterpreter();
      assertNotNull(string0);
      assertEquals("xU}_dz+L~w,M", music0.getName());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getPublisher());
      assertTrue(music0.isExplicit());
      assertEquals("xU}_dz+L~w,M", string0);
      assertEquals("", music0.getAlbum());
      assertEquals("", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getLyrics());
      assertEquals(1, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Music music0 = new Music("xU}_dz+L~w,M", "xU}_dz+L~w,M", "fhd`!W#v]<|ruHA'Q", "fhd`!W#v]<|ruHA'Q", "", (String) null, "", 1, true);
      int int0 = music0.getDuration();
      assertEquals("", music0.getMusicalFigures());
      assertEquals("xU}_dz+L~w,M", music0.getInterpreter());
      assertEquals("xU}_dz+L~w,M", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getPublisher());
      assertEquals(1, int0);
      assertEquals("", music0.getAlbum());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getLyrics());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, "5vZN8}ZUB", "5vZN8}ZUB", (String) null, "5vZN8}ZUB", (String) null, (-11), true);
      Music music1 = music0.clone();
      music0.setName("5vZN8}ZUB");
      boolean boolean0 = music1.equals(music0);
      assertFalse(music1.equals((Object)music0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Music music0 = new Music("FXAAdT", "FXAAdT", "FXAAdT", "FXAAdT", (String) null, "FXAAdT", "FXAAdT", 530, false);
      music0.setName((String) null);
      Music music1 = music0.clone();
      boolean boolean0 = music1.equals(music0);
      assertEquals(530, music1.getDuration());
      assertEquals(0, music1.getReproductions());
      assertFalse(music1.isExplicit());
      assertTrue(boolean0);
      assertEquals(530, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Music music0 = new Music("FXAAdT", "FXAAdT", "FXAAdT", "FXAAdT", (String) null, "FXAAdT", "FXAAdT", 530, false);
      Music music1 = music0.clone();
      boolean boolean0 = music1.equals(music0);
      assertTrue(boolean0);
      assertEquals(530, music1.getDuration());
      assertFalse(music1.isExplicit());
      assertEquals(530, music0.getDuration());
      assertEquals(0, music1.getReproductions());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Music music0 = new Music();
      boolean boolean0 = music0.equals(music0);
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Music music0 = new Music("xU}_dz+L~w,M", "xU}_dz+L~w,M", "fhd`!W#v]<|ruHA'Q", "fhd`!W#v]<|ruHA'Q", "", (String) null, "", 1, true);
      boolean boolean0 = music0.equals((Object) null);
      assertEquals(1, music0.getDuration());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getLyrics());
      assertEquals("", music0.getAlbum());
      assertEquals("", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
      assertEquals("xU}_dz+L~w,M", music0.getName());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getPublisher());
      assertFalse(boolean0);
      assertTrue(music0.isExplicit());
      assertEquals("xU}_dz+L~w,M", music0.getInterpreter());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Music music0 = new Music();
      assertFalse(music0.isExplicit());
      
      music0.setExplicit(true);
      music0.toString();
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Music music0 = new Music();
      String string0 = music0.toString();
      assertEquals("Nome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n", string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Music music0 = new Music();
      music0.setLyrics("");
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Music music0 = new Music("xU}_dz+L~w,M", "xU}_dz+L~w,M", "fhd`!W#v]<|ruHA'Q", "fhd`!W#v]<|ruHA'Q", "", (String) null, "", 1, true);
      music0.play();
      music0.clone();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Music music0 = new Music("xU}_dz+L~w,M", "xU}_dz+L~w,M", "fhd`!W#v]<|ruHA'Q", "fhd`!W#v]<|ruHA'Q", "", (String) null, "", 1, true);
      assertEquals("", music0.getMusicalFigures());
      
      music0.setMusicalFigures((String) null);
      music0.getMusicalFigures();
      assertEquals(1, music0.getDuration());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getLyrics());
      assertEquals("xU}_dz+L~w,M", music0.getInterpreter());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getPublisher());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getAlbum());
      assertTrue(music0.isExplicit());
      assertEquals("xU}_dz+L~w,M", music0.getName());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Music music0 = new Music("xU}_dz+L~w,M", "xU}_dz+L~w,M", "fhd`!W#v]<|ruHA'Q", "fhd`!W#v]<|ruHA'Q", "", (String) null, "", 1, true);
      assertEquals("", music0.getAlbum());
      
      music0.setAlbum((String) null);
      assertEquals("xU}_dz+L~w,M", music0.getInterpreter());
      assertEquals("xU}_dz+L~w,M", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getPublisher());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getLyrics());
      assertEquals(1, music0.getDuration());
      assertEquals("", music0.getMusicalFigures());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Music music0 = new Music("xU}_dz+L~w,M", "xU}_dz+L~w,M", "fhd`!W#v]<|ruHA'Q", "fhd`!W#v]<|ruHA'Q", "", (String) null, "", 1, true);
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getPublisher());
      
      music0.setPublisher((String) null);
      assertEquals("xU}_dz+L~w,M", music0.getInterpreter());
      assertTrue(music0.isExplicit());
      assertEquals("", music0.getMusicalFigures());
      assertEquals(1, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertEquals("xU}_dz+L~w,M", music0.getName());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getLyrics());
      assertEquals("", music0.getAlbum());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Music music0 = new Music();
      music0.setDuration((-2272));
      assertEquals(-2272, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Music music0 = new Music("xU}_dz+L~w,M", "xU}_dz+L~w,M", "fhd`!W#v]<|ruHA'Q", "fhd`!W#v]<|ruHA'Q", "", (String) null, "", 1, true);
      String string0 = music0.getPublisher();
      assertEquals("xU}_dz+L~w,M", music0.getName());
      assertNotNull(string0);
      assertEquals("fhd`!W#v]<|ruHA'Q", string0);
      assertEquals("xU}_dz+L~w,M", music0.getInterpreter());
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getMusicalFigures());
      assertEquals("", music0.getAlbum());
      assertEquals("fhd`!W#v]<|ruHA'Q", music0.getLyrics());
      assertEquals(1, music0.getDuration());
      assertTrue(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Music music0 = new Music("xU}_dz+L~w,M", "xU}_dz+L~w,M", "fhd`!W#v]<|ruHA'Q", "fhd`!W#v]<|ruHA'Q", "", (String) null, "", 1, true);
      assertEquals("xU}_dz+L~w,M", music0.getInterpreter());
      
      music0.setInterpreter("1adChmh");
      assertEquals("", music0.getMusicalFigures());
  }
}
