/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:17:15 GMT 2026
 */

package org.Model.Plan;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Plan.Plan;
import org.Model.Plan.PlanFree;
import org.Model.Plan.PlanPremiumBase;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PlanFree_ESTest extends PlanFree_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree((Plan) planPremiumBase0);
      planFree0.addPoints();
      assertEquals(5, planFree0.getPoints());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree((Plan) planPremiumBase0);
      boolean boolean0 = planFree0.hasAccessToFavorites();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree((Plan) planPremiumBase0);
      boolean boolean0 = planFree0.canAccessLibrary();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree((Plan) planPremiumBase0);
      String string0 = planFree0.toString();
      assertEquals("Plano: Free\n    Pontos: 0", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      assertEquals(0, planFree0.getPoints());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree((Plan) planPremiumBase0);
      boolean boolean0 = planFree0.canSkip();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree((Plan) planPremiumBase0);
      String string0 = planFree0.getPlanName();
      assertEquals("Free", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree((Plan) planPremiumBase0);
      boolean boolean0 = planFree0.canChooseWhatToPlay();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      PlanFree planFree0 = null;
      try {
        planFree0 = new PlanFree((Plan) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Plan.PlanFree", e);
      }
  }
}
