/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:15:19 GMT 2026
 */

package org.Model.Plan;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Plan.Plan;
import org.Model.Plan.PlanPremiumTop;
import org.Model.Plan.PlanTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PlanPremiumTop_ESTest extends PlanPremiumTop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      boolean boolean0 = planPremiumTop0.hasAccessToFavorites();
      assertEquals(0, planPremiumTop0.getPoints());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      boolean boolean0 = planPremiumTop0.canChooseWhatToPlay();
      assertTrue(boolean0);
      assertEquals(0, planPremiumTop0.getPoints());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      String string0 = planPremiumTop0.getPlanName();
      assertEquals(0, planPremiumTop0.getPoints());
      assertEquals("PremiumTop", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlanTest.TestPlan planTest_TestPlan0 = new PlanTest.TestPlan();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop((Plan) planTest_TestPlan0);
      boolean boolean0 = planPremiumTop0.canAccessLibrary();
      assertEquals(100, planPremiumTop0.getPoints());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlanTest.TestPlan planTest_TestPlan0 = new PlanTest.TestPlan();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop((Plan) planTest_TestPlan0);
      planPremiumTop0.addPoints();
      assertEquals(102, planPremiumTop0.getPoints());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      String string0 = planPremiumTop0.toString();
      assertEquals("Plano: PremiumTop\n    Pontos: 0", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      boolean boolean0 = planPremiumTop0.canSkip();
      assertEquals(0, planPremiumTop0.getPoints());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = null;
      try {
        planPremiumTop0 = new PlanPremiumTop((Plan) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Plan.PlanPremiumTop", e);
      }
  }
}
