/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 01 17:15:55 GMT 2026
 */

package org.Model.Plan;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.Model.Plan.Plan;
import org.Model.Plan.PlanPremiumBase;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PlanPremiumBase_ESTest extends PlanPremiumBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = null;
      try {
        planPremiumBase0 = new PlanPremiumBase((Plan) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Plan.PlanPremiumBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      String string0 = planPremiumBase0.getPlanName();
      assertEquals("PremiumBase", string0);
      assertEquals(0, planPremiumBase0.getPoints());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumBase planPremiumBase1 = new PlanPremiumBase((Plan) planPremiumBase0);
      assertEquals(0, planPremiumBase1.getPoints());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      boolean boolean0 = planPremiumBase0.hasAccessToFavorites();
      assertFalse(boolean0);
      assertEquals(0, planPremiumBase0.getPoints());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      boolean boolean0 = planPremiumBase0.canAccessLibrary();
      assertEquals(0, planPremiumBase0.getPoints());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      planPremiumBase0.addPoints();
      assertEquals(10, planPremiumBase0.getPoints());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      boolean boolean0 = planPremiumBase0.canChooseWhatToPlay();
      assertTrue(boolean0);
      assertEquals(0, planPremiumBase0.getPoints());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      boolean boolean0 = planPremiumBase0.canSkip();
      assertEquals(0, planPremiumBase0.getPoints());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      String string0 = planPremiumBase0.toString();
      assertEquals("Plano: PremiumBase\n    Pontos: 0", string0);
  }
}
