/*
 * This file was automatically generated by EvoSuite
 * Mon May 11 16:22:26 GMT 2026
 */

package org.Model.Album;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Album_ESTest extends Album_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("c", "c", (List<Music>) linkedList0);
      album0.removeMusic((Music) null);
      assertEquals("c", album0.getName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Album album0 = new Album("%JUPyUzsK5ol%U{BI", "$(cTQRy%M}='6");
      String string0 = album0.getName();
      assertEquals("%JUPyUzsK5ol%U{BI", string0);
      assertEquals("$(cTQRy%M}='6", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Album album0 = new Album();
      String string0 = album0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Album album0 = new Album((String) null, (String) null);
      String string0 = album0.getArtist();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Album album0 = new Album();
      String string0 = album0.getArtist();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("c", "c", (List<Music>) linkedList0);
      linkedList0.add((Music) null);
      album0.setMusics(linkedList0);
      // Undeclared exception!
      try { 
        album0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Album album0 = null;
      try {
        album0 = new Album((Album) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Album album0 = new Album((String) null, (String) null);
      String string0 = album0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album(" Me gk3#S~JZNU#|JM]", "org.Model.Album.Album", (List<Music>) linkedList0);
      String string0 = album0.getArtist();
      assertEquals(" Me gk3#S~JZNU#|JM]", album0.getName());
      assertEquals("org.Model.Album.Album", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Album album0 = new Album("_", "_");
      album0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        album0.getMusicByName("_");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Album album0 = new Album("_", "_");
      Music music0 = album0.getMusicByName("_");
      assertNull(music0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", "", (List<Music>) linkedList0);
      album0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        album0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", "", (List<Music>) linkedList0);
      String string0 = album0.toString();
      assertEquals("Album: \nArtista: \nM\u00FAsicas:\n", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Album album0 = new Album();
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      linkedList0.add((Music) null);
      album0.setMusics(linkedList0);
      // Undeclared exception!
      try { 
        album0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      linkedList0.add((Music) null);
      Album album0 = null;
      try {
        album0 = new Album("?", "?", (List<Music>) linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album(" Me gk3#S~JZNU#|JM]", "org.Model.Album.Album", (List<Music>) linkedList0);
      assertEquals(" Me gk3#S~JZNU#|JM]", album0.getName());
      
      album0.setName("org.Model.Album.Album");
      assertEquals("org.Model.Album.Album", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Album album0 = new Album((String) null, (String) null);
      Album album1 = album0.clone();
      assertNull(album1.getArtist());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album(" Me gk3#S~JZNU#|JM]", "org.Model.Album.Album", (List<Music>) linkedList0);
      assertEquals("org.Model.Album.Album", album0.getArtist());
      
      album0.setArtist("+r");
      assertEquals(" Me gk3#S~JZNU#|JM]", album0.getName());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.removeMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Album album0 = new Album();
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      album0.setMusics(linkedList0);
      List<Music> list0 = album0.getMusics();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Album album0 = new Album("+|Lg{jl!", "+|Lg{jl!");
      Album album1 = new Album(album0);
      assertFalse(album1.equals((Object)album0));
  }
}
