/*
 * This file was automatically generated by EvoSuite
 * Wed May 06 16:54:38 GMT 2026
 */

package org.Model.Album;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Album_ESTest extends Album_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Album album0 = new Album((String) null, "");
      String string0 = album0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Album album0 = new Album();
      String string0 = album0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("S _|9kKh]wj>C", (String) null, (List<Music>) linkedList0);
      String string0 = album0.getArtist();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Album album0 = new Album("", "");
      String string0 = album0.getArtist();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.removeMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Album album0 = new Album("M\u00FAsicas:\n", "M\u00FAsicas:\n");
      album0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        album0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Album album0 = null;
      try {
        album0 = new Album((Album) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Album album0 = new Album("", "");
      List<Music> list0 = album0.getMusics();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("\n", "Album: ", (List<Music>) linkedList0);
      String string0 = album0.getName();
      assertEquals("\n", string0);
      assertEquals("Album: ", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("\n", "Album: ", (List<Music>) linkedList0);
      String string0 = album0.getArtist();
      assertEquals("Album: ", string0);
      assertEquals("\n", album0.getName());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("\n", "Album: ", (List<Music>) linkedList0);
      Album album1 = new Album(album0);
      assertEquals("Album: ", album1.getArtist());
      assertEquals("\n", album1.getName());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Album album0 = new Album("Artista: ", "Artista: ");
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      linkedList0.add((Music) null);
      album0.setMusics(linkedList0);
      // Undeclared exception!
      try { 
        album0.getMusicByName("Artista: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("S _|9kKh]wj>C", (String) null, (List<Music>) linkedList0);
      Music music0 = album0.getMusicByName("Album: S _|9kKh]wj>C\nArtista: null\nM\u00FAsicas:\n");
      assertNull(music0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Album album0 = new Album("<\"n69Kw/Ut", "<\"n69Kw/Ut");
      album0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        album0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("S _|9kKh]wj>C", (String) null, (List<Music>) linkedList0);
      String string0 = album0.toString();
      assertEquals("Album: S _|9kKh]wj>C\nArtista: null\nM\u00FAsicas:\n", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Album album0 = new Album("M\u00FAsicas:\n", (String) null);
      album0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        album0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      linkedList0.add((Music) null);
      Album album0 = null;
      try {
        album0 = new Album("aX##", "aX##", (List<Music>) linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("\n", "Album: ", (List<Music>) linkedList0);
      assertEquals("\n", album0.getName());
      
      album0.setName("");
      assertEquals("Album: ", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("S _|9kKh]wj>C", (String) null, (List<Music>) linkedList0);
      album0.setArtist("Album: S _|9kKh]wj>C\nArtista: null\nM\u00FAsicas:\n");
      assertEquals("Album: S _|9kKh]wj>C\nArtista: null\nM\u00FAsicas:\n", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("\n", "Album: ", (List<Music>) linkedList0);
      album0.removeMusic((Music) null);
      assertEquals("\n", album0.getName());
      assertEquals("Album: ", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("S _|9kKh]wj>C", (String) null, (List<Music>) linkedList0);
      Album album1 = album0.clone();
      assertEquals("S _|9kKh]wj>C", album1.getName());
  }
}
