/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 14 13:25:39 GMT 2026
 */

package org.Model.Album;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Album_ESTest extends Album_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Album album0 = new Album("Artista: ", "Reproducoes: ");
      assertEquals("Reproducoes: ", album0.getArtist());
      assertEquals("Artista: ", album0.getName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Album album0 = new Album();
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      album0.setMusics(linkedList0);
      Album album1 = new Album(album0);
      assertEquals("", album1.getArtist());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", (String) null, (List<Music>) linkedList0);
      album0.removeMusic((Music) null);
      assertEquals("", album0.getName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", (String) null, (List<Music>) linkedList0);
      album0.setName((String) null);
      String string0 = album0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("Z [K0a", "Z [K0a", (List<Music>) linkedList0);
      String string0 = album0.getName();
      assertEquals("Z [K0a", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album((String) null, (String) null, (List<Music>) linkedList0);
      String string0 = album0.getArtist();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("Album: ", "Album: ", (List<Music>) linkedList0);
      String string0 = album0.getArtist();
      assertEquals("Album: ", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", "", (List<Music>) linkedList0);
      List<Music> list0 = linkedList0.subList(0, 0);
      linkedList0.clear();
      album0.setMusics(list0);
      // Undeclared exception!
      try { 
        album0.toString();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("D", "D", (List<Music>) linkedList0);
      album0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        album0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      List<Music> list0 = linkedList0.subList(0, 0);
      linkedList0.clear();
      Album album0 = null;
      try {
        album0 = new Album("", "", (List<Music>) list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Album album0 = new Album("47%QPHk!ZQr><G#!", "47%QPHk!ZQr><G#!");
      List<Music> list0 = album0.getMusics();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", (String) null, (List<Music>) linkedList0);
      String string0 = album0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Album album0 = new Album();
      String string0 = album0.getArtist();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Album album0 = new Album();
      Album album1 = null;
      try {
        album1 = new Album(album0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", "", (List<Music>) linkedList0);
      Music music0 = album0.getMusicByName("");
      assertNull(music0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Album album0 = new Album("47%QPHk!ZQr><G#!", "47%QPHk!ZQr><G#!");
      album0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        album0.getMusicByName("47%QPHk!ZQr><G#!");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album((String) null, (String) null, (List<Music>) linkedList0);
      String string0 = album0.toString();
      assertEquals("Album: null\nArtista: null\nM\u00FAsicas:\n", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("Iw|IjyNK\"Qy1U8&", "Iw|IjyNK\"Qy1U8&", (List<Music>) linkedList0);
      album0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        album0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Album album0 = new Album(";g8z![jPi(1", ";g8z![jPi(1");
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      linkedList0.addFirst((Music) null);
      album0.setMusics(linkedList0);
      // Undeclared exception!
      try { 
        album0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      linkedList0.add((Music) null);
      Album album0 = null;
      try {
        album0 = new Album("i", "i", (List<Music>) linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Album album0 = new Album(";g8z![jPi(1", ";g8z![jPi(1");
      album0.setArtist(";g8z![jPi(1");
      assertEquals(";g8z![jPi(1", album0.getName());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.removeMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", "", (List<Music>) linkedList0);
      Album album1 = album0.clone();
      assertEquals("", album1.getArtist());
  }
}
